logto-io/js

packages/client/src/index.test.ts
packages/client/src/index.ts

`@logto/client` is focused on browser, remove `extractBearerToken`

chore: remove extractBearerToken

---

packages/client/package.json
packages/client/src/discover.test.ts
packages/client/src/discover.ts
pnpm-lock.yaml

TBD: network error handling: [LOG-161](https://linear.app/silverhand/issue/LOG-161/op-request-%E9%94%99%E8%AF%AF%E5%A4%84%E7%90%86)

feat: discover

---

LICENSE
packages/client/package.json

feat: add license

---

packages/client/src/discover.ts
packages/client/src/grant-token.ts

Replace axios in method discover with opRequest

refactor: use opRequest in discover

---

.github/workflows/commitlint.yml
.husky/commit-msg
.husky/pre-commit
commitlint.config.js
package.json
pnpm-lock.yaml

Follow the [commitlint init doc](https://commitlint.js.org/#/./guides-local-setup?id=guides-local-setup)
Enable commitlint on the repo.  Add it to the husk pre-commit hook and  the  git workflow
[#LOG-170](https://linear.app/silverhand/issue/LOG-170/add-github-workflow-actions-to-js-repo)
Test locally with commit check 
@gao-sun @wangsijie

ci(js): add commitlint hook

---

packages/client/src/index.test.ts
packages/client/src/index.ts

method #getAccessToken
Return accessToken from tokenSet if is not expired, otherwise, use refreshToken to grant new accessToken
(LOG-221)
unit tests

feat: getAccessToken

---

packages/client/src/generators.test.ts

add cases from unit tests of  PkceTest.kt in log-io/kotlin

test: add cases to generators.test.ts

---

packages/client/package.json

fix(client): typings location

---

packages/client/src/generators.test.ts

fix: rm unnecessary console.log in unit tests

---

packages/client/src/index.test.ts
packages/client/src/index.ts
packages/client/src/request-login.test.ts
packages/client/src/request-login.ts
packages/client/src/utils.test.ts
packages/client/src/utils.ts

- The developers can use custom `scope` value.
- LogtoClient can correct the value of `scope` from parameters.

feat: custom scope

---

packages/client/src/index.test.ts
packages/client/src/index.ts

A util to check if current webpage state is `login callback`
`isLoginRedirect` in `index.test.ts`

feat: isLoginRedirect

---

packages/client/src/index.ts
packages/client/src/request-login.test.ts
packages/client/src/request-login.ts

Make `getLoginUrlAndCodeVerifier` parameters more readable.

refactor: extract LoginPrepareParameters

---

packages/client/src/generators.test.ts
packages/client/src/generators.ts

I got some new understanding of code verifier after re-reading https://datatracker.ietf.org/doc/html/rfc7636#section-4.1
So correct some code.

refactor: generators.ts

---

packages/client/src/constants.ts
packages/client/src/generators.test.ts
packages/client/src/generators.ts
packages/client/src/grant-token.test.ts
packages/client/src/index.ts
packages/client/src/session-manager.ts
packages/client/src/storage.ts
packages/client/src/utils.test.ts
packages/client/src/utils.ts
packages/client/src/verify-id-token.ts

Gather constants into a file -- `constants.ts`

refactor: extract constants

---

packages/client/src/constants.ts
packages/client/src/index.test.ts
packages/client/src/session-manager.test.ts

Extracted common constants to `constants.ts` and forgot to replacing related constants in `*.test.ts`.
So replace common constants in `*.test.ts` now.
Pass all existing unit tests.

test: import constants.ts

---

packages/playground/README.md

Update the playground readme file
as we integrate the playground with `logtoClient` which take OIDC domain instead of the full url as its input config.  
Readme only no need to test

docs(playground): update readme

---

packages/react/README.md
packages/react/jest.config.js
packages/react/package.json
packages/react/src/context.tsx
packages/react/src/index.tsx
packages/react/src/provider.tsx
packages/react/src/use-logto.spec.tsx
packages/react/src/use-logto.ts
packages/react/tsconfig.json
pnpm-lock.yaml

init package `@logto/react`
a simple unit test is added.

feat(react): init provider & hook

---

packages/playground/package.json
packages/playground/razzle.config.js
pnpm-lock.yaml

clean up unused dependencies and reduce the package size limit to 300kb
clean up unused dependencies:
- ky
- zod
reduce the bundle size limit to 300kb
build success without any errors. UT case passed
@wangsijie cc: @IceHe @gao-sun @xiaoyijun

chore(playground): clean up unused dependencies

---

packages/client/src/constants.ts
packages/client/src/generators.ts
packages/client/src/utils.test.ts
packages/client/src/utils.ts

- generators.ts
- Package all existing exports into `Generators`
- Export default `Generators`
- utils.ts
- Fix method `UrlSafeBase64.encode` (originaly `encodeBase64`)
- Fix method `UrlSafeBase64.decode` (originaly `decodeBase64`)
- Pass all existing unit tests.
- Assert `rawContent = decode(encode(rawContent))`

refactor(js): generators.ts and utils.ts

---

packages/client/package.json
packages/client/src/generators.ts
packages/client/src/utils.test.ts
packages/client/src/utils.ts
packages/playground/package.json
packages/playground/razzle.config.js
packages/react/package.json
pnpm-lock.yaml

- Reuse the implementation of UrlSafeBase64 from @silverhand/essentials
- Update package `@silverhand/essentials` version from v1.1.0 to v1.1.1
- Replace utils/UrlSafeBase64 with @silverhand/essentials/UrlSafeBase64
- Remove utils/UrlSafeBase64 and its unit tests
- Pass all existing unit tests

refactor(client): replace utils/UrlSafeBase64 with @silverhand/essentials/UrlSafeBase64

---

packages/react/package.json
packages/react/src/ProtectedRoute.spec.tsx
packages/react/src/ProtectedRoute.tsx
pnpm-lock.yaml

`<ProtectedRoute path="/">xxx</ProtectedRoute>`
When user enters secure route (protected route), will trigger login process automatically, ensure that only see content in login state.
[LOG-231](https://linear.app/silverhand/issue/LOG-231/react-react-router)
`ProtectedRoute.spec.ts`

feat: protected route

---

packages/react/package.json
packages/react/tsconfig.json

add build script: run tsc to generate lib files

chore(react): build script

---

packages/client/src/parse-callback.test.ts
packages/client/src/parse-callback.ts
packages/client/src/request-login.test.ts

- Simplify `parseRedirectCallback` method and `request-login.test.ts` tests
- See [discussions](https://silverhand-io.slack.com/archives/C02A8G4HVAM/p1636957110000100) for more in Slack.
- Pass all existing tests.

refactor(client): simplify parseRedirectCallback and request-login.test.ts

---

packages/react/package.json
packages/react/src/index.tsx
packages/react/tsconfig.json

This PR includes following updates:
export `PrivateRouter` & `useLogto` out
update tsc build type to es5
add prepublish script
log-282
no need to test
@wangsijie

feat(react-sdk): update react sdk

---

packages/client/src/index.ts
packages/react/src/ProtectedRoute.spec.tsx
packages/react/src/auth-state.ts
packages/react/src/provider.tsx
packages/react/src/reducer.ts
packages/react/src/use-logto.spec.tsx

Map claims to context
see unit tests

chore(react): add claims to context

---

packages/client/src/index.test.ts
packages/client/src/utils.test.ts
packages/client/src/utils.ts

add method of generateCallbackUri() to utils
[Linear LOG-238](https://linear.app/silverhand/issue/LOG-238/js-add-utils-to-generate-callback-url)
add uni-tests to utils.test.ts and pass all the tests

chore: add generateCallbackUri() method to utils

---

packages/client/package.json
packages/playground/package.json
packages/react-playground/package.json
packages/react/package.json
pnpm-lock.yaml

add lint-stage hook to all packages, lint all packages before commit. 
config change no business logic updates
@wangsijie @gao-sun cc: @darcyYe

feat(lint): add lint-stage to all packages

---

packages/client/src/api/discover.ts
packages/client/src/api/grant-token.test.ts
packages/client/src/api/grant-token.ts
packages/client/src/index.ts
packages/client/src/modules/token-set.ts

- refactor(client): rename OIDCConfiguration to OidcConfigResponse
- refactor(client): rename TokenSetParameters to TokenResponse
Notes: 
- Defer to add the basic type `UserInfoResponse` when adding the core function `fetchUserInfo`.
- Split `js/client` into `js/js` and `js/browser` later.

refactor(client): rename to OidcConfigResponse and TokenResponse

---

packages/client/src/index.ts
packages/client/src/modules/token-set.ts
packages/client/src/utils/id-token.test.ts
packages/client/src/utils/id-token.ts
packages/react/src/auth-state.ts
packages/react/src/reducer.ts

- Rename `IDToken` to `IdTokenClaims`
- Reference: [IdTokenClaims](https://www.notion.so/silverhand/9c1fbcd630fc44adaa45a6d7d686326a?v=3cea92e2906048d287a8648b76c73c65)
- Rename `decodeToken` to `decodeIdToken`
- Reference: [decodeIdToken](https://www.notion.so/silverhand/decodeIdToken-7b3b739c397a431882a2e41bac8782f1)
- Add necessary optional claims to `IdTokenClaims`
- Reference: [ID Token Claims](https://www.notion.so/silverhand/OIDC-ec922f42788a41a69f5e2550a2f7c3fe#4ffdd579db9b473d8876ce870fcdaede)
- Update code related to ID Token
Notes:
- The standard claims will be added later when implementing `UserInfoResponse` of `fetchUserInfo`.
- Reference: [Standard Claims](https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims)
---
@logto-io/eng

refactor(client): decodeIdToken

---

packages/js/package.json
packages/js/src/index.test.ts
packages/js/src/index.ts
packages/js/src/utils/generators.test.ts
packages/js/src/utils/generators.ts
pnpm-lock.yaml

- Add generators
- generateState
- generateCodeVerifier
- generateCodeChallenge
LOG-1354
- generateState:
- result should be random value
- generateCodeVerifier
- result should be random value
- generateCodeChallenge
- should generate different codeChallenge with different code verifiers
- should generate same codeChallenge with same code verifiers
---
@logto-io/eng

feat(js): generate state, code verifier and code challenge

---

packages/js/package.json
packages/js/src/utils/generators.test.ts
pnpm-lock.yaml

- Replace isUrlSafe with UrlSafeBase64.isSafe
- Upgrade `essentials` version from 1.1.2 to 1.1.3
LOG-1378
LOG-1380

chore(js): replace isUrlSafe with UrlSafeBase64.isSafe

---

packages/js/package.json
packages/js/src/index.ts
packages/js/src/utils/id-token.test.ts
packages/js/src/utils/id-token.ts
pnpm-lock.yaml

- Add utility function `decodeIdToken`
- Add basic type `IdTokenClaims`
Related #126 
LOG-1355
LOG-1357
- decode valid JWT → return claims
- decode invalid JWT → throw Error
- decode valid JWT without some claim (e.g. `iss`) → throw StructError
---
@logto-io/eng

feat(js): decodeIdToken

---

packages/js/src/utils/generators.test.ts

Remove unnecessary comment in unit tests
Related to LOG-1355
Pass all existing tests
---
@logto-io/eng

chore(js): remove unnecessary comment in unit tests

---

packages/js/package.json
packages/js/src/utils/errors.ts
packages/js/src/utils/id-token.test.ts
packages/js/src/utils/id-token.ts
pnpm-lock.yaml

- Add `verifyIdToken`
- Custom Error `LogtoError`
LOG-1356
- valid ID Token should not throw
- mismatched signature should throw
- mismatched issuer should throw
- mismatched audience should throw
- expired ID Token should throw
- issued at time, too far away from current time, should throw
---
@logto-io/eng

feat(js): verifyIdToken

---

packages/js/package.json
packages/js/src/utils/errors.ts
pnpm-lock.yaml

- refactor(js): replace Normalize with NormalizeKeyPaths from @silverhand/essentials
Related PR: https://github.com/silverhand-io/essentials/pull/6
LOG-1399
LOG-1401
---
@logto-io/eng

refactor(js): replace Normalize with NormalizeKeyPaths

---

packages/js/package.json
packages/js/src/utils/callback-uri.test.ts
packages/js/src/utils/callback-uri.ts
packages/js/src/utils/errors.test.ts
packages/js/src/utils/errors.ts
packages/js/src/utils/id-token.test.ts
packages/js/src/utils/id-token.ts
pnpm-lock.yaml

- Add verifyAndParseCodeFromCallbackUri
- Add getMessageByErrorCode
LOG-765
---
@logto-io/eng

feat(js): verifyAndParseCodeFromCallbackUri

---

packages/client/package.json
packages/js/package.json
packages/playground/package.json
pnpm-lock.yaml

update node-fetch version
hot fix the github dependent bot warning
@logto-io/eng

fix(js): hot fix dependent bot warning 

---

packages/js/package.json
packages/js/src/consts/index.ts
packages/js/src/core/fetch-token.test.ts
packages/js/src/core/fetch-token.ts
pnpm-lock.yaml

Implement js core function: fetchTokenByRefreshToken
https://linear.app/silverhand/issue/LOG-771/fetch-tokens-by-refresh-token

feat(js): fetchTokenByRefreshToken

---

packages/js/src/utils/errors.ts

- chore(js): remove unnecessary logto error codes
LOG-651
Pass all existing tests
---
@logto-io/eng

chore(js): remove unnecessary logto error codes

---

packages/playground/jest.setup.js

Resolve eslint errors in jest.setup.js in playground package, by providing disable & enable pairs.

chore(playground): resolve eslint errors by providing disable & enable pairs

---

packages/js/package.json
packages/js/src/core/fetch-token.test.ts

add jsdom test script to `test:coverage` in `js`. not using GitHub Actions matrix since it's for one package only.
UT
@logto-io/eng

test(js): add test script for jsdom

---

packages/js/package.json
packages/js/src/core/oidc-config.test.ts
packages/js/src/core/oidc-config.ts
pnpm-lock.yaml

- Add core core function fetchOidcConfig
- Add type OidcConfigResponse
LOG-766
---
@logto-io/eng

feat(js): fetchOidcConfig

---

packages/js/src/core/sign-out.test.ts
packages/js/src/core/sign-out.ts

Provide js core function: generateSignOutUri
Passed all unit tests

feat(js): core function generateSignOutUri

---

packages/js/src/core/sign-out.test.ts
packages/js/src/core/sign-out.ts

Refactor core function `generateSignOutUri`, in order to align the implementation of `generateSignInUri`
[LOG-1455](https://linear.app/silverhand/issue/LOG-1455/refactor-js-core-sign-out)

refactor(js): core function generateSignOutUri

---

packages/js/src/core/sign-in.test.ts
packages/js/src/core/sign-in.ts
packages/js/src/utils/scopes.test.ts
packages/js/src/utils/scopes.ts

- feat(js): scopes
- feat(js): generateSignInUri
---
Related PR: #149 
LOG-768
---
@logto-io/eng

feat(js): scopes and generateSignInUri

---

packages/js/src/core/user-info.test.ts
packages/js/src/core/user-info.ts

feat(js): fetchUserInfo
LOG-1124
---
@eng

feat(js): fetchUserInfo

---

packages/js/src/core/revoke.test.ts
packages/js/src/core/revoke.ts

feat(js): revoke
LOG-464
---
@logto-io/eng

feat(js): revoke

---

packages/js/src/core/fetch-token.test.ts
packages/js/src/core/fetch-token.ts
packages/js/src/core/oidc-config.ts
packages/js/src/core/user-info.test.ts
packages/js/src/core/user-info.ts

refactor(js): use required parameter Requester
LOG-1461
Pass all existing tests
---
@logto-io/eng

refactor(js): use required parameter Requester

---

.github/pull_request_template.md

- Fix typo in the GitHub PR template: you → your
None
No Need.
---
@logto-io/eng

chore: fix type in the GitHub PR template

---

packages/js/src/core/index.ts
packages/js/src/index.ts
packages/js/src/utils/index.ts

[chore(js): export in index.ts](https://github.com/logto-io/js/commit/6e4e52cf85fce88749f7ff7f946bf91835218309)
None
---
@logto-io/eng

chore(js): export in index.ts

---

packages/js/src/core/fetch-token.ts
packages/js/src/core/oidc-config.ts
packages/js/src/core/revoke.ts
packages/js/src/core/sign-in.ts
packages/js/src/core/user-info.ts
packages/js/src/utils/callback-uri.ts
packages/js/src/utils/requester.ts

- chore(js): shorten imports
- refactor(js): replace interface with type
- Reference: https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#differences-between-type-aliases-and-interfaces
- Discussion: https://silverhand-io.slack.com/archives/C02A8G4HVAM/p1644231317277599
None.
Pass all existing tests
---
@logto-io/eng

refactor(js): shorten imports and replace interface with type

---

packages/js/src/consts/index.ts
packages/js/src/core/fetch-token.test.ts
packages/js/src/core/fetch-token.ts

Fetch access token by authorization code

feat(js): fetch access token by authorization code

---

packages/js/src/consts/index.ts
packages/js/src/core/revoke.ts
packages/js/src/core/sign-out.ts

[refactor(js): replace query-string with URLSearchParams](https://github.com/logto-io/js/commit/21c9ab458f1db3226805bc3e4285c9774e661a1d)
LOG-1462
LOG-1460
---
@logto-io/eng

refactor(js): replace specific strings with QueryKey.*

---

packages/browser/jest.config.js
packages/browser/jest.setup.js
packages/browser/package.json
packages/browser/src/index.test.ts
packages/browser/src/index.ts
pnpm-lock.yaml

- feat(browser): add LogtoClient constructor
- test(browser): construct LogtoClient
LOG-786
---
@logto-io/eng

feat(browser): add LogtoClient constructor

---

packages/js/jest.setup.js
packages/js/src/utils/generators.ts

- [chores(js): add TODO comments about generateCodeChallenge and crypto](https://github.com/logto-io/js/pull/172/commits/757d2d41309673ac51e73787fec80524c60acffc)
---
See related [comments](https://github.com/logto-io/js/pull/170#discussion_r804356352) in #170 
Related LOG-790
---
@logto-io/eng

chore(js): add TODO comments about generateCodeChallenge and crypto

---

packages/browser/jest.config.js
packages/client/jest.config.js
packages/js/jest.config.js
packages/playground/razzle.config.js
packages/react-playground/razzle.config.js
packages/react/jest.config.js

Noticed jest coverage reports are not covering all the files. 
update jest coverage settings
ut passed 
recover viewed locally
playground etc. 
@logto-io/eng

fix(ut): update jest coverage configs

---

packages/browser/jest.setup.js
packages/browser/package.json
packages/browser/src/index.test.ts
packages/browser/src/index.ts
packages/js/package.json
packages/js/src/index.ts
packages/js/src/utils/callback-uri.ts
pnpm-lock.yaml

Main:
- feat(browser): signIn
- test(browser): signIn
---
Chores:
- chore(js,browser): add exports in package.json
- Fix webpack failure: [discussion](https://silverhand-io.slack.com/archives/C02A8G4HVAM/p1644473115488029) on Slack
- chore(js,browser): replace npm with pnpm in package.json
- feat(js): export consts
- feat(js): export parseUriParameters
---  
Next up:
- `handleCallback`
LOG-790
---
@logto-io/eng

feat(browser): signIn

---

packages/browser/jest.setup.js
packages/client/jest.setup.js

chore(js,browser): improve lint comments in jest.setup.js
---
before:
after:
None
No need.
---
@logto-io/eng

chore(js,browser): improve lint comments in jest.setup.js

---

packages/js/jest.setup.js
packages/react-playground/jest.setup.js

chore: improve the lint comments in all jest.setup.js
---
Fix the similar lint comments in all packages ( where #176 missed )
---
before:
after:
None
No need.
---
@logto-io/eng

chore: improve the lint comments in all jest.setup.js

---

packages/browser/src/index.ts

Implemented `isAuthenticated` getter method in LogtoClient.
We consider the user is authenticated when we have gained/loaded the ID token successfully.

feat(browser): isAuthenticated getter method

---

packages/browser/src/index.ts

Provide sign out method in browser sdk
LOG-793
Test cases will be provided in another PR that links to LOG-1245

feat(browser): sign out

---

packages/browser/src/index.ts

Improve browser sign out logic
[LOG-793](https://linear.app/silverhand/issue/LOG-793/browser-sign-out-method)

refactor(browser): sign out

---

packages/browser/src/index.ts

Read `idToken` and `refreshToken` from local storage and set it to `LogtoClient` instance on initialize.

refactor(browser): read tokens from local storage on init

---

packages/js/src/utils/id-token.ts

refactor(js): decodeIdToken
- replace `superstruct.create` with `superstruct.assert`
---
Since `create` is different from `assert` in `superstruct`
- [assert](https://docs.superstructjs.org/api-reference/core#assert): just validate
- [create](https://docs.superstructjs.org/api-reference/core#create): validate, fill with default values and etc.
- with [coercions](https://docs.superstructjs.org/api-reference/coercions): defaulted and trimmed
LOG-1355
---
@logto-io/eng

refactor(js): decodeIdToken

---

packages/browser/src/index.test.ts

Add unit test cases for sign out in browser SDK
[LOG-1571](https://linear.app/silverhand/issue/LOG-1571/add-unit-test-cases-for-browser-sign-out)

test(browser): add browser sign out test cases

---

packages/browser/src/index.test.ts

Resolve master branch build failure.

refactor(browser): resolve failed tests

---

packages/browser/package.json
packages/browser/src/errors.ts
packages/browser/src/index.test.ts
packages/browser/src/index.ts
packages/browser/src/utils/index.ts
pnpm-lock.yaml

Provide getter functions for browser SDK
* isAuthenticated
* getAccessToken
* getIdTokenClaims
* fetchUserInfo
Build succeeded. Test cases will be added in a follow-up PR.

feat(browser): browser end user information getters

---

packages/browser/src/index.ts

refactor(browser): remove unnecessary renamed imports
LOG-796
---
@logto-io/eng

refactor(browser): remove unnecessary renamed imports

---

packages/browser/src/index.ts
packages/browser/src/utils/index.test.ts
packages/browser/src/utils/index.ts

- refactor(browser): extract *Token key builder utils
---
- Follow the principle `Single Source Of Truth`.
- Since `index.ts` (LogtoClient) source code is too long, extract code from it.
LOG-796
LOG-882 (needed next)
LOG-793
Pass all existing tests and
---
@logto-io/eng

refactor(browser): extract *Token key builder utils

---

package.json
packages/browser/package.json
packages/js/package.json
packages/playground/package.json
packages/react-playground/package.json
packages/react/package.json
pnpm-lock.yaml

Bump versions:
* typescript => 4.5.5
* configs => 0.8.1
N/A

chore: bump version of typescript and configs

---

packages/browser/package.json
packages/browser/src/index.test.ts
packages/client/package.json
packages/client/src/index.ts
packages/client/src/modules/storage.test.ts
packages/client/src/utils/generators.ts
packages/js/package.json
packages/playground/package.json
packages/playground/src/App.tsx
packages/playground/src/LogtoClientContext.ts
packages/react-playground/package.json
packages/react/package.json
packages/react/src/ProtectedRoute.spec.tsx
packages/react/src/provider.tsx
packages/react/src/use-logto.spec.tsx
pnpm-lock.yaml

Bump eslint-config to 0.9.1
Build succeeded

chore: bump eslint-config to 0.9.1

---

packages/react-sample/package.json
packages/react-sample/src/App.module.scss
packages/react-sample/src/App.tsx
packages/react-sample/src/include.d/react-app.d.ts
packages/react-sample/src/index.html
packages/react-sample/src/index.tsx
packages/react-sample/tsconfig.json
pnpm-lock.yaml

Add sample project for Logto React SDK
Build succeeded

feat(react-sample): init react sample project

---

packages/browser/src/errors.ts
packages/browser/src/index.test.ts
packages/browser/src/index.ts

- feat(browser): handle sign-in callback
- test(browser): handle sign-in callback
- fix(browser): getAccessToken
LOG-882
---
@logto-io/eng

feat(browser): handle sign-in callback 

---

packages/browser/src/index.test.ts

Add unit test cases for LogtoClient information getter functions
* getAccessToken
* getIdTokenClaims
* fetchUserInfo

test(browser): add unit test cases for LogtoClient getters

---

package.json
packages/browser-sample/package.json
packages/browser-sample/public/index.html
packages/browser-sample/src/app.js
packages/browser-sample/src/app.scss
packages/browser-sample/src/consts.js
packages/browser-sample/src/index.js
packages/browser-sample/src/index.scss
packages/browser-sample/src/pages/Callback.js
packages/browser-sample/src/pages/Home.js
pnpm-lock.yaml

Create browser sample project pages by using browser SDK and vanilla js.

feat(browser-sample): add browser sample pages

---

packages/react/jest.config.ts
packages/react/package.json
packages/react/src/index.test.ts
packages/react/src/index.ts
packages/react/tsconfig.build.json
packages/react/tsconfig.json
pnpm-lock.yaml

- refactor(react): init react package
LOG-1600
Related:
LOG-1627 #204 
LOG-1628 #203 
Temporary tests for now.

refactor(react): init react package

---

packages/browser/package.json
packages/browser/webpack.config.js
packages/js/package.json
packages/js/src/index.ts
packages/js/webpack.config.js
pnpm-lock.yaml

- chore(browser): simplify webpack config
- chore(js): simplify webpack config
- chore(js): code coverage excludes src/index.ts
Related: LOG-1600 #201 [comment](https://github.com/logto-io/js/pull/201#discussion_r815626626)
---
@logto-io/eng

chore(js,browser): simplify wepack config & code coverage excludes src/index.ts

---

packages/browser/src/index.test.ts
packages/browser/src/index.ts

Provide a new method in LogtoClient to check if the sign-in redirect URI has been redirected by OIDC provider.

feat(browser): check if sign-in redirect URI has been redirected

---

packages/react/package.json
packages/react/src/context.tsx
packages/react/src/hooks/index.test.tsx
packages/react/src/hooks/index.ts
packages/react/src/index.test.ts
packages/react/src/index.ts
packages/react/src/provider.tsx
packages/react/tsconfig.build.json
pnpm-lock.yaml

Provide SPA React SDK with Logto context provider and `useLogto` hook.
[LOG-649](https://linear.app/silverhand/issue/LOG-649/jsreact)

feat(react): react SDK with context provider

---

packages/react-sample/package.json
packages/react-sample/src/App.module.scss
packages/react-sample/src/App.tsx
packages/react-sample/src/RequireAuth.ts
packages/react-sample/src/consts/index.ts
packages/react-sample/src/pages/Callback/index.tsx
packages/react-sample/src/pages/Home/index.module.scss
packages/react-sample/src/pages/Home/index.tsx
packages/react-sample/src/pages/ProtectedResource/index.tsx
pnpm-lock.yaml

feat(react-sample): add react sample webpages

---

packages/react/src/context.tsx
packages/react/src/hooks/index.ts

Improve error handling in React SDK
[LOG-1854](https://linear.app/silverhand/issue/LOG-1854/declare-a-standardized-error-class-in-react-context)

refactor(react): declare a re-usable error thrower in logto context

---

packages/react-sample/src/pages/Home/index.tsx

Fix table style issue in React sample project
[LOG-1863](https://linear.app/silverhand/issue/LOG-1863/fix-table-style-issue-in-react-sample-project)

fix(react-sample): table style not applied issue

---

packages/browser/src/index.test.ts

Add endpoint assertions in browser SDK unit tests
[LOG-1861](https://linear.app/silverhand/issue/LOG-1861/add-endpoint-assertions-in-browser-sdk-unit-tests)

test(browser): add endpoint assertions in browser sdk tests

---

.github/workflows/publish.yml
packages/browser-sample/package.json
packages/browser/package.json
packages/js/package.json
packages/react-sample/package.json
packages/react/package.json

add publish script
to test in Actions

ci: publish script

---

commitlint.config.js
lerna.json
package.json
pnpm-lock.yaml

fix publish workflow errors
to test in Actions

fix: publish workflow

---

.github/workflows/commitlint.yml
.github/workflows/main.yml
.github/workflows/publish.yml

upgrade node workflow version to use node 16 as default
CI

ci: upgrade node workflow

---

packages/browser/tsconfig.json
packages/js/tsconfig.json

- remove `target: es5`
- remove `lib`
CI

chore: update `tsconfig.json`

---

packages/browser/package.json
packages/js/package.json
packages/react/package.json

Add github repository URLs for `@logto/js`, `@logto/browser` and `@logto/react` SDKs.
To see in npmjs.com

chore: add github repository urls

---

packages/react-sample/src/App.tsx
packages/react/src/hooks/index.test.tsx
packages/react/src/index.ts
packages/react/src/provider.tsx

chores:
* export type `LogtoConfig` from `@logto/react` SDK
* bump typescript version to 4.6.2

chore: export LogtoConfig type

---

packages/browser/src/index.test.ts
packages/browser/src/index.ts

cache get access token promises by resource key to avoid race condition
LOG-1901
UT

refactor(browser): cache get access token promises by resource

---

packages/browser/src/index.test.ts
packages/browser/src/index.ts

- refactor(browser): delete expired access token in getAccessToken
- test(browser): delete expired access token in getAccessToken
Related PR #229 [comment](https://github.com/logto-io/js/pull/229#discussion_r826959443)
LOG-1909

refactor(browser): delete expired access token in getAccessToken

---

packages/browser/package.json
packages/browser/src/index.test.ts
packages/browser/src/index.ts
pnpm-lock.yaml

feat(browser): reuse remote jwks and odic config
LOG-1909
Pass all existing tests and
---
@logto-io/eng

feat(core): reuse remote jwk set and oidc config

---

.github/workflows/publish.yml
package.json

`prepack` -> `prerelease` to avoid build issue, related #235

fix: manually run script before publish

---

pnpm-lock.yaml

chore: update pnpm-lock

---

packages/vue/jest.config.ts
packages/vue/package.json
packages/vue/src/consts.ts
packages/vue/src/context.ts
packages/vue/src/index.test.ts
packages/vue/src/index.ts
packages/vue/src/plugin.ts
packages/vue/tsconfig.build.json
packages/vue/tsconfig.json
pnpm-lock.yaml

Create Logto SDK for Vue3
[LOG-2569](https://linear.app/silverhand/issue/LOG-2569/create-vue-sdk)

feat(vue): create vue sdk

---

packages/browser/src/index.ts
packages/react/src/index.ts
packages/vue/src/index.ts

Export more types and classes from SDKs for better type support in client apps
N/A

refactor: export more types and classes from SDKs

---

packages/react/src/hooks/index.ts
packages/vue/src/plugin.ts

refactor: update comments

---

packages/js/src/core/user-info.ts

Update `UserInfoResponse` type
N/A

refactor(js): update UserInfoResponse type

---

package.json
pnpm-lock.yaml

Remove `conventional-changelog-conventionalcommits` dependency
N/A

chore: remove conventional-changelog-conventionalcommits

---

.github/pull_request_template.md

remove Linear issue reference in PR template
No need.

chore: remove Linear issue reference in PR template

---

packages/js/src/utils/id-token.test.ts
packages/js/src/utils/id-token.ts

since we have `null` in id token claims (name, username)
UT added

fix(js): support null in id token

---

packages/browser/src/index.ts
packages/react/src/index.ts
packages/vue/src/index.ts

refactor: export `Prompt`

---

.github/workflows/publish.yml
package.json

- update git to bot user
- leverage version script to remove extra commit
locally

ci: update publish workflow

---

.github/workflows/commitlint.yml
.github/workflows/main.yml

update workflows to make publish workflow works
after merge

ci: update workflows

---

packages/js/src/utils/errors.ts
packages/js/src/utils/generators.test.ts
packages/js/src/utils/generators.ts

Optimize error message for unavailable `crypto.subtle` in insecure contexts

feat(js): optimize error message for unavailable crypto.subtle in insecure contexts

---

packages/browser/src/errors.ts
packages/js/jest.setup.js
packages/js/src/utils/errors.ts

Remove unnecessary todo comments
No need.

chore(js,browser): remove unnecessary todo comments

---

packages/client/jest.config.ts
packages/client/jest.setup.js
packages/client/package.json
packages/client/src/errors.ts
packages/client/src/index.test.ts
packages/client/src/index.ts
packages/client/src/mock.ts
packages/client/src/storage.ts
packages/client/src/utils/index.test.ts
packages/client/src/utils/index.ts
packages/client/tsconfig.json
pnpm-lock.yaml

Extract 3 platform-related parts from `@logto/browser` and get a new package `@logto/client`:
1. requester
2. storage
3. handleRedirect
Next action: refactor `@logto/browser` to extend `@logto/client`.
Passed all UTs.

feat(client): add client package

---

packages/client/src/index.ts
packages/node/jest.config.ts
packages/node/package.json
packages/node/src/include.d/node-fetch.d.ts
packages/node/src/index.test.ts
packages/node/src/index.ts
packages/node/src/utils/generators.test.ts
packages/node/src/utils/generators.ts
packages/node/tsconfig.json
pnpm-lock.yaml

New package: node
Extended from `client`, implement 4 adapters: `requester`, `generateCodeChallenge`, `generateCodeVerifier`, `generateState`.
Leave `storage` and `navigate` to users.
UTs.

feat(node): node sdk

---

packages/vue-sample/package.json
pnpm-lock.yaml

chore(deps): upgrade vite

---

.github/pull_request_template.md

use default community health files from [logto-io/.github](https://github.com/logto-io/.github).
N/A

chore: use default community health files

---

packages/next-sample/pages/api/sign-in-callback.ts
packages/next/src/index.test.ts
packages/next/src/index.ts

add sign in callback route handler
UTs and sample

feat(next): add sign in callback route

---

packages/next-sample/libraries/fetch-json.ts
packages/next-sample/package.json
packages/next-sample/pages/_app.tsx
packages/next-sample/pages/api/protected-resource.ts
packages/next-sample/pages/api/user.ts
packages/next-sample/pages/index.tsx
packages/next/package.json
packages/next/src/index.test.ts
packages/next/src/index.ts
packages/next/src/types.ts
pnpm-lock.yaml

Add function: `withLogtoApiRoute`: read and assign auth state to `request`.
UTs and sample.

feat(next): with logto api route

---

packages/next-sample/pages/index.tsx
packages/next-sample/pages/protected.tsx
packages/next-sample/vercel.json

Implement full sample of Next.js
Local tested.

feat(next-sample): implement nextjs sample

---

packages/next/package.json
pnpm-lock.yaml

fixing missing peer deps
locally run `pnpm lerna version` ok

chore(deps): add react to next package

---

README.md

Add Next.js introduction to README
No need

docs: add nextjs to readme

---

packages/js/src/utils/errors.test.ts
packages/js/src/utils/errors.ts

Improve error messages
- Since the original error messages are too concise (even the error messages are shorter than the related error codes) and ambiguous.
N/A

chore(js): improve error messages

---

packages/js/src/utils/errors.ts

Remove unused error code
Build successfully and pass the existing tests.

chore(js): remove unused error code

---

packages/client/src/types/index.ts
packages/next-sample/libraries/logto.ts
packages/node/src/index.ts

Add support for OIDC's `client_secret`, it is called `appSecret` here.
Local tested.

feat(node): support client secret

---

packages/react/README.md

chore: update react sdk readme

---

packages/vue/README.md

chore: update vue sdk readme

---

packages/js/README.md

chore(js): add README.md

---

packages/browser/README.md

chore: add browser sdk readme

---

packages/express/jest.config.ts
packages/express/package.json
packages/express/src/errors.ts
packages/express/src/index.test.ts
packages/express/src/index.ts
packages/express/src/storage.test.ts
packages/express/src/storage.ts
packages/express/src/test-utils.ts
packages/express/src/types.ts
packages/express/tsconfig.json
pnpm-lock.yaml

Init express SDK and implement handle routes:
1. sign-in
2. sign-in-callback
3. sign-out
UTs and local tested with real express app.

feat(express): init express and add routes handler

---

packages/client/src/mock.ts

refactor(client): remove unused constants

---

packages/express-sample/package.json
packages/express-sample/src/app.ts
packages/express-sample/src/logto.ts
packages/express-sample/tsconfig.json
pnpm-lock.yaml

Implement express sample.
Local tested

feat(express-sample): add express sample code

---

packages/next/README.md

Add Next.js readme.
No needed.

docs(next): add readme

---

packages/express/README.md

Add express readme file.
No needed

docs(express): add readme

---

packages/client/README.md

Add readme file for @logto/client
No needed.

docs(client): add readme

---

packages/node/README.md

Add readme file for "node"
No needed.

docs(node): add readme

---

packages/browser-sample/src/pages/Home.js

Fix compilation errors in browser sample project and make sign-in work again! :-)

fix(browser-sample): make sign-in work again

---

packages/react-sample/src/RequireAuth.ts
packages/react/src/provider.tsx
packages/vue/src/context.ts

Fixed the mis-handled `isAuthenticated` state in React and Vue SDKs, which was introduced in 1.0.0-beta.3 and has caused sign-in issues in admin console and demo-app.

fix(react,vue): fix mis-handled isAuthenticated state in react and vue sdks

---

packages/vue-sample/vite.config.ts

Change default port number to 3000 in Vue sample project

chore(vue-sample): change default port number to 3000

---

packages/client/src/errors.ts
packages/client/src/index.test.ts
packages/client/src/index.ts
packages/client/src/mock.ts
packages/js/src/core/index.ts
packages/js/src/core/oidc-config.test.ts
packages/js/src/core/oidc-config.ts
packages/js/src/core/user-info.test.ts
packages/js/src/core/user-info.ts

Enable user endpoint in JS core and client SDKs

feat(js,client): enable user endpoint in js core and client sdks

---

packages/browser-sample/src/pages/Home.js
packages/browser/src/index.ts
packages/react-sample/src/pages/Home/index.tsx
packages/react/src/hooks/index.test.tsx
packages/react/src/hooks/index.ts
packages/react/src/index.ts
packages/vue-sample/src/views/HomeView.vue
packages/vue/src/index.test.ts
packages/vue/src/index.ts
packages/vue/src/plugin.ts

Enable userinfo endpoint in Browser, React and Vue SDKs, and provide `fetchUserInfo()` method to return `UserInfoResponse`.

feat(browser,react,vue): enable user endpoint in browser sdk family

---

packages/client/src/index.test.ts
packages/client/src/index.ts
packages/client/src/mock.ts
packages/client/src/types/index.ts
packages/express/src/index.ts
packages/next/src/index.ts

Remove `persistAccessToken` from configs, it is no longer configuable.
UTs

fix: remove persist access token

---

package.json
packages/client/package.json
packages/client/src/index.test.ts
packages/client/src/index.ts
packages/client/src/types/index.ts
packages/client/src/utils/requester.ts
packages/js/package.json
packages/js/src/utils/arbitrary-object.ts
packages/js/src/utils/errors.test.ts
packages/js/src/utils/errors.ts
packages/js/src/utils/id-token.test.ts
packages/js/src/utils/id-token.ts
packages/js/src/utils/index.ts
pnpm-lock.yaml

Remove superstruct, replaced with own type check functions.
The package "superstruct" is "es module" and can not be "required" in some circumstances, we can fix it by setting "alias", but our users will have that problem too.
UTs.

refactor(js,client): remove superstruct

---

packages/client/package.json
packages/js/package.json
pnpm-lock.yaml

Bump core-kit to v1.0.0-beta.14, in order to avoid a potential build failure when using utilities in browser

chore: bump core-kit to v1.0.0-beta.14

---

packages/client/README.md

docs(client): fix link on readme

---

README.md

This PR adds just a note about the Remix SDK in the readme

docs: adds note about the Remix SDK

---

packages/express-sample/src/app.ts
packages/express/src/index.ts
packages/express/src/types.ts
packages/next-sample/pages/api/protected-resource.ts
packages/next/src/index.ts
packages/next/src/types.ts
packages/node/src/index.test.ts
packages/node/src/index.ts
packages/node/src/types.ts
packages/remix/src/index.ts
packages/remix/src/infrastructure/logto/get-context.ts
packages/remix/src/useCases/getContext/GetContextController.spec.ts
packages/remix/src/useCases/getContext/GetContextController.ts
packages/remix/src/useCases/getContext/GetContextUseCase.spec.ts
packages/remix/src/useCases/getContext/GetContextUseCase.ts
packages/remix/src/useCases/getContext/index.ts

Add the ability to get target resource's access token for those SDKS: node, next, express
UTs and local tested with samples.

feat(node,next,express): get access token with resource

---

packages/next-sample/pages/profile-ssr.tsx
packages/node/src/index.ts

fix "undefined" issue in getServerSideProps
Local tested

fix(next-sample): fix undefined in getServerSideProps

---

packages/remix/README.md

changes `@openformation/logto-remix` to `@logto/remix` and `includeAccessToken` to `getAccessToken`
Not needed

docs: use correct import and parameter

---

packages/next-sample/package.json
packages/next-sample/pages/index.tsx
packages/next-sample/pages/protected.tsx
pnpm-lock.yaml

Upgrade to next 13.
UTs and local tested

feat(next-sample): upgrade to next 13

---

packages/js/src/core/user-info.ts
packages/js/src/utils/id-token.test.ts
packages/js/src/utils/id-token.ts

Remove all `role_names` since it's deprecated.
UTs

fix: remove deperecated role names

---

packages/browser-sample/src/consts.js
packages/client/src/index.test.ts
packages/client/src/index.ts
packages/express-sample/src/app.ts
packages/js/src/core/sign-out.test.ts
packages/js/src/core/sign-out.ts
packages/next-sample/libraries/logto.ts
packages/react-sample/src/consts/index.ts
packages/vue-sample/src/consts/index.ts

replace idTokenHint with clientId in signOut URI
UT updated
test locally

refactor(js): replace idTokenHint with clientId in sign out URI

---

packages/vue/src/index.test.ts

Add unit test case for `fetchUserInfo` in Vue SDK, also making sure that it won't cause infinite loop in the SDK level.

test(vue): add test case for fetchUserInfo

---

packages/client/src/errors.ts
packages/client/src/index.ts

Remove unnecessary error handlings from `@logto/client` SDK, in order to report more specific error messages to the end users.
After the change, instead of having ambiguous messages like "Invalid Id Token", we now have the specific reason why the Id Token is invalid.

refactor(client): remove unnecessary error handling

---

packages/browser/jest.config.ts
packages/browser/package.json
packages/browser/tsconfig.test.json
packages/client/jest.config.ts
packages/client/package.json
packages/client/tsconfig.test.json
packages/js/jest.config.ts
packages/js/package.json
packages/js/tsconfig.test.json
packages/node/jest.config.ts
packages/node/package.json
packages/node/tsconfig.test.json
packages/remix/jest.config.ts
pnpm-lock.yaml

upgrade @silverhand/essentials package
CI

chore: upgrade essentials

---

.changeset/cold-pugs-knock.md
.changeset/hot-dogs-bake.md

chore: add changesets

---

packages/browser-sample/package.json
packages/browser/package.json
packages/client/package.json
packages/express-sample/package.json
packages/express/package.json
packages/next-app-dir-sample/package.json
packages/next-sample/package.json
packages/next/package.json
packages/node/package.json
packages/react-sample/package.json
packages/react/package.json
packages/remix/package.json
packages/vue-sample/package.json
packages/vue/package.json
pnpm-lock.yaml

use workspace protocol to be more specific about workspace dependencies
local install/build ok

refactor: use workspace protocol

---

packages/express-sample/package.json
packages/express-sample/src/app.ts
packages/express-sample/tsconfig.json
pnpm-lock.yaml

fix express sample project: use tsc to start project, fix "profile" link.
Local tested
OR

fix: fix express sample project

---

packages/browser/package.json
packages/client/package.json
packages/express/package.json
packages/js/package.json
packages/node/package.json
packages/react/package.json
packages/remix/package.json
packages/vue/package.json

build before test make publish workflow happy
after merge

ci: build before publish

---

packages/next-app-dir-sample/libraries/config.ts
packages/next-sample/libraries/config.ts

remove https for localhost default value
OR

fix(next-sample): remove https for localhost default value

---

packages/browser-sample/package.json
packages/react-sample/package.json
pnpm-lock.yaml

chore(deps): upgrade parcel

---

packages/client/src/index.constructor.test.ts
packages/client/src/index.sign-in.test.ts
packages/client/src/index.sign-out.test.ts
packages/client/src/index.test.ts

split the huge index test file
/

refactor(client): reorg tests

---

.changeset/curvy-ways-confess.md
packages/react/src/hooks/index.test.tsx
packages/react/src/hooks/index.ts
packages/vue/src/index.test.ts
packages/vue/src/index.ts

Fix potential failure when handling sign-in callback in React and Vue SDKs. Should fix #508 and may also fix #516 
UT

fix: unexpected error when handling sign-in callback in React and Vue SDKs

---

.changeset/cyan-apples-fold.md

Update changeset message for a previous bug fix.
N/A

chore: update changeset message

---

packages/client/src/adapter/types.ts
packages/client/src/index.ts
packages/client/src/types/index.ts
packages/client/src/utils/requester.ts
packages/js/src/consts/index.ts
packages/js/src/types/index.ts

add comment annotations for better dev experience.
N/A

refactor: add comments

---

.changeset/dull-scissors-walk.md
packages/express/src/index.test.ts
packages/express/src/index.ts
packages/express/src/types.ts

For express SDK: Add support for custom auth routes prefix.
Local tested and UTs
OR

feat(express): support custom auth routes prefix

---

.changeset/modern-flies-kick.md
packages/next-sample/pages/api/edge.ts
packages/next-sample/pages/api/logto-edge/sign-in-callback.ts
packages/next-sample/pages/api/logto-edge/sign-in.ts
packages/next-sample/pages/api/logto-edge/sign-out.ts
packages/next-sample/pages/api/logto-edge/user.ts
packages/next/edge/index.ts

Fix potential bug: `request.url` may not be accurent if the app is running behand reverse proxy, use `config.baseUrl` to auto fix.
Local tested with next sample.
OR

fix(next): fix request url mismatch

---

README.md

Update sample project links in README
N/A
~~- [ ] `.changeset`~~
~~- [ ] docs~~
OR

chore: update sample project links in readme

---

packages/express/README.md
packages/next/README.md

Remove broken links in READMEs.
Local preview.

fix: remove broken links

---

.changeset/thick-humans-breathe.md

chore: add changeset

---

.changeset/dull-suits-learn.md
.gitignore
packages/next-sample/package.json
packages/next-server-actions-sample/.eslintrc.json
packages/next-server-actions-sample/README.md
packages/next-server-actions-sample/app/callback/page.tsx
packages/next-server-actions-sample/app/layout.tsx
packages/next-server-actions-sample/app/page.tsx
packages/next-server-actions-sample/app/sign-in.tsx
packages/next-server-actions-sample/app/sign-out.tsx
packages/next-server-actions-sample/libraries/logto.ts
packages/next-server-actions-sample/next-env.d.ts
packages/next-server-actions-sample/next.config.js
packages/next-server-actions-sample/package.json
packages/next-server-actions-sample/tsconfig.json
packages/next/jest.config.js
packages/next/package.json
packages/next/rollup.config.js
packages/next/server-actions/index.test.ts
packages/next/server-actions/index.ts
packages/next/src/session.ts
packages/next/src/types.ts
packages/next/tsconfig.build.json
packages/next/tsconfig.json
pnpm-lock.yaml

Add new sub-package `@logto/next/server-actions`, now Logto's Next SDK supports the new feature [Server Actions](https://nextjs.org/docs/app/api-reference/functions/server-actions).
A new example package also added.
Local tested with the example project.

feat(next): add server actions support

---

packages/next-app-dir-sample/app/layout.tsx
packages/next-app-dir-sample/app/nav.tsx
packages/next-sample/pages/_app.tsx
packages/next-sample/pages/profile-ssr.tsx
packages/next-server-actions-sample/app/callback/page.tsx
packages/next-server-actions-sample/app/layout.tsx
packages/react-sample/package.json
packages/react-sample/src/App.module.scss
packages/react-sample/src/App.tsx
packages/react-sample/src/RequireAuth.tsx
packages/react-sample/src/pages/Home/index.tsx
packages/react-sample/src/pages/ReactQuery/index.tsx
packages/react/package.json
pnpm-lock.yaml

- to demonstrate the usage in react-query
- update next types
- disable `react/prefer-read-only-props` for now as it's a breaking change

feat: add react-query sample

---

.changeset/stupid-mails-sniff.md
packages/capacitor/src/index.ts
packages/express/src/index.ts
packages/next/src/index.ts
packages/node/src/index.ts
packages/remix/src/index.ts
packages/vue/src/index.ts

align exports across packages not touched in #580 
n/a

refactor: align exports across packages

---

.changeset/cyan-cherries-speak.md
.changeset/plenty-shirts-teach.md
packages/client/src/index.sign-in.test.ts
packages/client/src/index.ts
packages/client/src/mock.ts
packages/react/src/hooks/index.test.tsx
packages/react/src/hooks/index.ts

refactor function to reduce unnecessary calls and prevent bugs.
- added unit tests
- locally tested with demo. all update functions will only execute once

refactor(client,react): memoize and cache methods

---

.changeset/wet-bulldogs-attend.md
packages/next-sample/libraries/config.ts
packages/next-sample/pages/api/organizations.ts
packages/next-sample/pages/index.tsx
packages/next-server-actions-sample/app/page.tsx
packages/next-server-actions-sample/libraries/logto.ts
packages/next/edge/index.ts
packages/next/server-actions/index.test.ts
packages/next/server-actions/index.ts
packages/next/src/index.test.ts
packages/next/src/index.ts

For Next.js SDK and the corresponding edge SDK:
- Set the methods of getting node client to public, in order that the user can access all the SDK features like organizations.
- Add examples of organizations to sample project.
Local tested

feat(next): support organizations

---

.changeset/chilly-donuts-shout.md
.changeset/honest-experts-leave.md
.vscode/settings.json
packages/client/src/index.ts
packages/react-sample/package.json
packages/vue-sample/package.json
packages/vue-sample/src/consts/index.ts
packages/vue-sample/src/main.ts
packages/vue-sample/src/router/index.ts
packages/vue-sample/src/views/HomeView.vue
packages/vue-sample/src/views/OrganizationsView.vue
packages/vue-sample/src/views/ProtectedResourceView.vue
packages/vue/package.json
packages/vue/src/index.test.ts
packages/vue/src/index.ts
packages/vue/src/plugin.ts
pnpm-lock.yaml

Add support to organizations in Vue SDK

feat(vue): add organization support

---

packages/next-sample/pages/profile-ssr.tsx

use new approach of redirect, see https://github.com/logto-io/docs/pull/543
Local tested
~~- [ ] `.changeset`~~
~~- [ ] necessary TSDoc comments~~

fix(next-sample): use new approach of redirect

---

.changeset/odd-pianos-invite.md
packages/express-sample/src/app.ts
packages/express/src/index.ts
packages/node/src/client.ts
packages/node/src/index.test.ts
packages/node/src/types.ts

Add orgnazition support to Express SDK.
Local tested.

feat(express,node): add organization support to express

---

packages/express/README.md
packages/next/README.md

Update READMEs for express and next.js.
N/A

docs(express,next): update readme

---

packages/browser/README.md
packages/react/README.md
packages/vue/README.md

Update README for `@logto/browser`, `@logto/react` and `@logto/vue` SDKs
N/A
~~- [ ] `.changeset`~~
~~- [ ] necessary TSDoc comments~~

chore: update readme

---

.husky/commit-msg
.husky/pre-commit
package.json
packages/remix/package.json
pnpm-lock.yaml

my commit hooks always fail locally. this can fix it.
local commit

chore: upgrade husky and commitlint

---

jest.config.js
packages/sveltekit/jest.config.js
packages/sveltekit/package.json
packages/sveltekit/src/__mocks__/@sveltejs/kit.ts
packages/sveltekit/src/cookie-storage.test.ts
packages/sveltekit/src/cookie-storage.ts
packages/sveltekit/src/index.test.ts
packages/sveltekit/src/index.ts
packages/sveltekit/tsconfig.json
pnpm-lock.yaml

- add test cases for sveltekit sdk
- use p-queue to save session data to avoid concurrency issues
the pull itself

refactor: add test cases

---

.changeset/mighty-waves-wait.md
packages/angular-sample/README.md
packages/sveltekit-sample/README.md
packages/sveltekit-sample/package.json
packages/sveltekit/README.md
packages/sveltekit/package.json
packages/sveltekit/src/cookie-storage.ts
packages/sveltekit/src/index.ts

chore: add sveltekit content

---

packages/browser-sample/src/consts.js
packages/browser-sample/src/index.js
packages/browser-sample/src/pages/Callback.js
packages/browser-sample/src/pages/Home.js

Update the browser-sample to include 
- getAccessToken
- getOrganizationToken
test locally

feat: upate the browser-sample

---

packages/node/src/utils/cookie-storage.test.ts

as it causes random ci failures
ci

refactor: remove random delay in tests

---

.gitignore
packages/next/package.json
packages/next/src/index.ts
packages/node/package.json
packages/node/src/exports.ts
packages/node/src/index.ts
packages/nuxt/README.md
packages/nuxt/package.json
packages/nuxt/playground/app.vue
packages/nuxt/playground/nuxt.config.ts
packages/nuxt/playground/package.json
packages/nuxt/playground/server/tsconfig.json
packages/nuxt/playground/tsconfig.json
packages/nuxt/src/module.ts
packages/nuxt/src/runtime/composables/use-logto-client.ts
packages/nuxt/src/runtime/composables/use-logto-user.ts
packages/nuxt/src/runtime/server/event-handler.ts
packages/nuxt/src/runtime/server/tsconfig.json
packages/nuxt/src/runtime/utils/constants.ts
packages/nuxt/src/runtime/utils/types.ts
packages/nuxt/tsconfig.json
packages/sveltekit-sample/src/hooks.server.ts
packages/sveltekit/src/index.ts
packages/vue-sample/package.json
packages/vue/package.json
pnpm-lock.yaml

> [!Note]
> You may find the project structure, toolkit, and configuration are not similar to other packages, the reason is nuxt has many conventions (more specifically, convention over configuration), and we have to follow them. omg.
- implement workable nuxt sdk
- tested with playground
locally tested sign-in/out (the playground project prints correct info)
changeset, tests, comments, etc. are coming in the following pulls.

feat: init nuxt sdk

---

.changeset/tiny-ghosts-double.md
packages/nuxt/README.md
packages/nuxt/package.json
packages/nuxt/playground/app.vue
packages/nuxt/playground/nuxt.config.ts
packages/nuxt/src/module.ts
packages/nuxt/src/runtime/composables/use-logto-client.ts
packages/nuxt/src/runtime/composables/use-logto-user.ts
packages/nuxt/src/runtime/utils/constants.ts
packages/nuxt/src/runtime/utils/types.ts
packages/nuxt/test/event-handler.test.ts
packages/nuxt/test/setup.ts
packages/nuxt/vitest.config.ts
pnpm-lock.yaml

add basic unit tests for nuxt sdk
the pull itself

test: add nuxt tests

---

.changeset/few-pets-shave.md
packages/nuxt/playground/app.vue

add brackets and semicolon for clarity
/

chore: fix typo in sample

---

.changeset/brave-eels-love.md
packages/nuxt/playground/app.vue
packages/nuxt/playground/nuxt.config.ts
packages/nuxt/src/runtime/server/event-handler.ts

fixes #650
- turn off auto import for simulating the real environment
- fix issues accordingly

fix(nuxt): turn off auto import and fix issues

---

.changeset/mighty-lamps-cough.md
jest.config.js
package.json
packages/nuxt/package.json
packages/nuxt/test/event-handler.test.ts
packages/sveltekit/package.json
packages/sveltekit/src/__mocks__/@sveltejs/kit.ts
packages/sveltekit/src/index.test.ts
packages/sveltekit/tsconfig.json
pnpm-lock.yaml

- add `test:coverage` scripts to missing packages (nuxt, sveltekit)
- fix test cases
ci

refactor: fix test cases

---

.changeset/pretty-lamps-wave.md
packages/js/src/core/sign-in.ts
packages/js/src/types/index.ts

- removed misplaced `@deprecated`
- add `@experimental` marks
n/a

refactor: fix jsdoc comments

---

.changeset/spicy-bobcats-brush.md
packages/next/src/index.test.ts
packages/next/src/index.ts

Add error handler to withLogtoApiRoute, this is useful when developers need to handle the auth failed case.
Unit tests.

feat(next): add error handler to withLogtoApiRoute

---

.changeset/dry-pants-draw.md
packages/browser/src/index.ts
packages/capacitor/src/index.ts
packages/client/src/shim.ts
packages/express/src/index.ts
packages/next/edge/index.ts
packages/next/src/index.ts
packages/node/src/exports.ts
packages/react/src/index.ts
packages/remix/src/index.ts
packages/sveltekit/src/index.ts
packages/vue/src/index.ts

Export more typescript types from js sdk fmily
CI
~~- [ ] necessary TSDoc comments~~

refactor: export more types from js sdks

---

package.json
packages/browser-sample/package.json
packages/browser/package.json
packages/capacitor/package.json
packages/client/package.json
packages/express-sample/package.json
packages/express/package.json
packages/js/package.json
packages/next-app-dir-sample/package.json
packages/next-sample/package.json
packages/next/package.json
packages/node/package.json
packages/nuxt/package.json
packages/passportjs-sample/package.json
packages/react-sample/package.json
packages/react/package.json
packages/remix/package.json
packages/sveltekit/package.json
packages/vue-sample/package.json
packages/vue/package.json
pnpm-lock.yaml

get rid of annoying warnings
no warning + ci ok

chore(deps): upgrade packages

---

.changeset/curly-clocks-love.md
README.md
packages/chrome-extension-sample/README.md
packages/chrome-extension-sample/static/manifest.json
packages/chrome-extension/package.json

- fix `@logto/chrome-extension` publish config
- add README for Chrome extension sample
- update main readme
n/a

refactor: update chrome extension packages

---

.changeset/clever-turkeys-deliver.md
packages/client/src/client.ts
packages/client/src/index.sign-in.test.ts

Clear access token as well on sign-in.
Unit test

fix(client): clear access token storage on sign-in

---

.changeset/loud-horses-enjoy.md
packages/client/src/client.ts
packages/client/src/index.test.ts
packages/react/src/hooks/index.test.tsx
packages/react/src/hooks/index.ts
packages/vue/src/index.test.ts
packages/vue/src/index.ts
packages/vue/src/plugin.ts

Export `clearAccessToke()` method from Client, React and Vue SDKs.
Unit tests

feat(client,react,vue): export clearAccessToken method

---

.changeset/bright-queens-grin.md
packages/client/src/client.ts
packages/client/src/index.test.ts
packages/react/src/hooks/index.test.tsx
packages/react/src/hooks/index.ts
packages/vue/src/index.test.ts
packages/vue/src/index.ts
packages/vue/src/plugin.ts

Add a new SDK method to clear all cached tokens (ID token, refresh token and access token) from storage.
UT

feat(client,react,vue): add new SDK method to clear all cached tokens

---

.changeset/many-dots-fly.md
packages/next/src/index.ts

fixed #686
Export type `LogtoNextConfig` in next.js sdk.
N/A

feat(next): export type LogtoNextConfig

---

.changeset/weak-cows-hope.md
packages/next/server-actions/index.ts

fixed #701
support custom redirectUri for handleSignIn function in Server Actions.
Local tested.

fix(next): support customize redirectUri in handleSignIn

---

packages/next/server-actions/index.ts

Make 2 function signatures for `handleSignIn`:
```
export function handleSignIn(config: LogtoNextConfig, searchParams: URLSearchParams): Promise<void>;
export function handleSignIn(config: LogtoNextConfig, url: URL): Promise<void>;
```
Local tested and existing tests should pass.

fix(next): change handleSignIn param number to 2

---

.changeset/fresh-needles-hang.md
.changeset/spotty-ligers-argue.md
packages/client/src/types/index.test.ts
packages/client/src/types/index.ts
packages/js/src/core/sign-in.test.ts
packages/js/src/core/sign-in.ts
packages/js/src/utils/angular.ts
packages/js/src/utils/scopes.test.ts
packages/js/src/utils/scopes.ts

allow the full control of scopes
added unit tests

refactor: allow no reserved scopes

---

.changeset/lemon-plants-lay.md
packages/next/src/index.ts

Add a param to `handleAuthRoutes`, allowing users to handle errors.
Existing tests should pass.

feat(next): add error handler to handleAuthRoutes

---

.changeset/honest-hornets-jump.md
packages/nuxt/package.json
packages/nuxt/src/runtime/server/event-handler.ts
pnpm-lock.yaml

Wrap `fetchUserInfo` with `trySafe` to avoid throwing. When the token expires, this request will fail and throw an error, this error is hard to catch. Developers may check the existance of `user` to check if the user is authenticated.
Existing tests should pass.

fix(nuxt): return undefined instead of throwing for fetch user info

---

package.json
packages/browser/package.json
packages/capacitor/package.json
packages/client/package.json
packages/express/package.json
packages/js/package.json
packages/next/package.json
packages/node/package.json
packages/nuxt/package.json
packages/react/package.json
packages/remix/package.json
packages/sveltekit/package.json
packages/vue/package.json
pnpm-lock.yaml

upgrade vitest and set concurrent to 2 to avoid test failures in ci
https://github.com/logto-io/js/actions/runs/9706547785?pr=745

chore: upgrade vitest

---

.changeset/clever-dancers-teach.md
packages/nuxt/src/runtime/server/event-handler.ts

use `trySafe` for all `context.logtoUser` methods to align the behavior on user fetching
n/a (unit tests should be added later)

refactor(nuxt): use `trySafe` for all `context.logtoUser` methods

---

.github/workflows/main.yml
package.json

- remove `--parallel` for script executing since it ignores the workspace dependency relationship
- add vitest segfault retry to improve job running stability
ci

chore: update scripts

---

packages/express/package.json
packages/sveltekit/package.json
pnpm-lock.yaml

chore(deps): upgrade swc

---

.github/workflows/main.yml

avoid manual retries
looks slightly better

ci: add test retries

---

.changeset/strong-singers-approve.md

- version bumping should be major as it's a breaking change
- fix typo
n/a

chore: update changeset

---

.changeset/clever-zoos-scream.md
.changeset/real-bears-glow.md
packages/capacitor/src/index.ts
packages/express/src/index.ts
packages/js/src/core/user-info.ts
packages/next/edge/index.ts
packages/next/src/index.ts
packages/remix/src/index.ts

- Update `UserInfoResponse` type definition, adding `organization_data` claim. Fixes #758 
- Fix an issue that some SDKs are not exporting `UserInfoResponse` type
N/A

fix: update userinfo response type

---

.changeset/shy-files-remain.md
packages/next/src/index.test.ts
packages/next/src/index.ts
packages/next/src/types.ts
packages/next/src/utils.ts

For Next.js App router, add an optional parameter "onError" to all methods.
Existing tests should pass, local tested.

feat(next): add error handlers to all methods

---

packages/remix/README.md

This PR fixes documentation for remix v2. It took me some time to do research and fix this, even though the fix was simple. So I fixed the docs so someone else can get started right away.
The only thing I changed is the README.md file inside the remix package, so I haven't run any test.

docs: correct the docs to run on remix v2

---

.changeset/little-dragons-push.md
packages/next-sample/pages/api/logto-edge/sign-in.ts
packages/next/edge/index.ts
packages/next/server-actions/client.ts
packages/next/server-actions/index.ts
packages/next/src/client.ts
packages/next/src/index.test.ts
packages/next/src/index.ts

Apply the new sign in options of base JS SDK, the sign in function now receive an object parameter.
Local tested with 2 sample projects, and the `login_hint` works as expected.

feat(next): apply new sign in options

---

.changeset/olive-olives-kiss.md
packages/express/src/index.ts
packages/express/src/types.ts

Support sign in options.
Local tested.

feat(express): support sign in options

---

.changeset/tricky-dolls-cover.md
packages/nuxt/src/runtime/server/event-handler.ts
packages/nuxt/src/runtime/utils/types.ts
packages/nuxt/test/event-handler.test.ts

Support sign in options.
Local tested.

feat(nuxt): support sign in options

---

packages/browser/package.json
packages/client/package.json
packages/js/package.json
packages/node/package.json
packages/nuxt/package.json
packages/react/package.json
packages/vue/package.json
pnpm-lock.yaml

chore: bump essentials to v2.9.2

---

.changeset/smart-melons-swim.md
.github/workflows/publish.yml
.scripts/publish.sh
.scripts/version.sh

Debug the root cause of the recent release failures. We can see an error message from the CI logs:

chore: debug release issue

---

.github/workflows/publish.yml
.gitignore
.scripts/publish.sh
.scripts/version.sh
packages/next-sample/next-env.d.ts
packages/next-server-actions-sample/next-env.d.ts

- Fix SDK publish failure caused by auto-generated files by Next.js in the build-time. The uncommitted generated files prevented the publish CLI from being executed properly, and reported an "Unclean working tree" error.
Those generated d.ts files have been removed and added to the `.gitignore` config
- Keep the `git status` check in workflow for future debugging purposes, in case there is a similar issue

chore: fix SDK publish failure

---

package.json
pnpm-lock.yaml

- Fix more security vulnerabilities.
- Keep the `pnpm.overrides` in order to prevent a possible regression

fix: security vulnerabilities

---

packages/next/server-actions/index.ts

Add JSDoc to `searchParamsOrUrl`.
N/A

chore(next): add jsdoc to searchParamsOrUrl

---

packages/nuxt/package.json
packages/nuxt/playground/nuxt.config.ts
packages/nuxt/src/module.ts
packages/nuxt/tsconfig.json
pnpm-lock.yaml

Bump nuxt dependencies to resolve this issue:
```
[nitro] [unhandledRejection] pushWarningContext is not a function
```
Local tested, playground runs well.

chore(nuxt): bump nuxt dependencies

---

.changeset/green-donkeys-decide.md
packages/nuxt/package.json
packages/nuxt/playground/nuxt.config.ts
packages/nuxt/src/module.ts
packages/nuxt/src/runtime/server/event-handler.ts
packages/nuxt/src/runtime/utils/handler.ts
packages/nuxt/tsconfig.json
pnpm-lock.yaml

Export `logtoEventHandler` so that users can use Logto in middelware like:
```ts
import { defineEventHandler, useRuntimeConfig } from '#imports';
import { logtoEventHandler } from '@logto/nuxt';
export default defineEventHandler(async (event) => {
const config = useRuntimeConfig(event);
await logtoEventHandler(event, config);
console.log(event.context.logtoUser, event.context.logtoClient);
});
```
Local tested.

feat(nuxt): export event handler

---

packages/client/README.md

chore: update client sdk readme

---

.changeset/new-weeks-visit.md
packages/js/src/consts/index.ts
packages/js/src/core/sign-in.test.ts
packages/js/src/core/sign-in.ts

Add support to the one-time token in `SignInUriParameters` type definition.
UT

refactor(js): support one-time token in sign-in URI params

---

packages/js/CHANGELOG.md

fix(js): fix changelog typo

---

.changeset/heavy-bananas-invite.md
packages/remix/src/useCases/handleSignInCallback/HandleSignInCallbackController.ts

fixed #916
fix URL protocol replacement in HandleSignInCallbackController to prevent 'httpss' URLs
Local tested.

fix(remix): fix the https replacement

---

packages/nuxt/package.json
pnpm-lock.yaml

Update nuxt related packages, to fix the version mismatch issue when running playground.
Local tested.

chore(deps): update nuxt package versions

---

packages/remix-sample/README.md
packages/remix-sample/app/root.tsx
packages/remix-sample/app/routes/_index.tsx
packages/remix-sample/app/routes/access-token.tsx
packages/remix-sample/app/routes/api.logto.$action.ts
packages/remix-sample/app/routes/user-info.tsx
packages/remix-sample/app/services/auth.server.ts
packages/remix-sample/package.json
packages/remix-sample/tsconfig.json
packages/remix-sample/vite.config.ts
packages/remix/README.md
pnpm-lock.yaml

Add Remix sample project.
Local tested.

feat: add remix sample project

---

packages/node/README.md

update README with a general guide of implementing SDKs
N/A

docs(node): update README with a general guide of implementing SDKs

---

package.json
pnpm-lock.yaml

This PR contains result of `pnpm audit --fix` to resolve https://github.com/logto-io/js/security/dependabot/110

chore(deps): fix base-x to a non-vulnerable version

---

packages/next-sample/README.md
packages/next-sample/package.json
packages/next-server-actions-sample/README.md
packages/next-server-actions-sample/package.json
pnpm-lock.yaml

This PR fixes the "deploy with Vercel" button:
1. Fix package path
2. Remove optional envs
3. Use `latest` instead of `workspace`
Tested with Vercel.

chore: fix deploy with vercel button

---

.changeset/unlucky-fireants-appear.md
packages/js/src/consts/openid.ts

Add address to UserScope enum.
Local tested.

feat(js): add address scope

---

.github/CONTRIBUTING.md

fixed #920
Add contributing guide.
N/A

chore: add contributing guide

---

package.json
pnpm-lock.yaml

fix: audit fix security issue
