logto-io/js

- packages/client/src/token-set.test.ts
- packages/client/src/token-set.ts
- packages/client/src/utils.ts
class TokenSet, store token parameters and parse id_token claims.
ut: `token-set.test.ts`
> feat: token-set

- packages/client/jest.config.js
- packages/client/jest.setup.js
- packages/client/package.json
- packages/client/src/index.test.ts
- packages/client/src/token-set.test.ts
- packages/client/src/utils.test.ts
- packages/client/src/verify-id-token.test.ts
- packages/client/src/verify-id-token.ts
- pnpm-lock.yaml
in jose 3.x, module can only be imported by subpath, it could cause problems in both jsdom and webpack.
change log from jose 4.x:
> All module named exports have moved from subpaths to just "jose". For example, import { jwtVerify } from 'jose/jwt/verify' is now just import { jwtVerify } from 'jose'.
old unit tests.
> chore: upgrade jose to 4.x

- packages/client/tsconfig.json
commonjs is more generic than es6
> fix: tsc commonjs

- packages/client/package.json
- pnpm-lock.yaml
https://github.com/logto-io/js/security/dependabot/packages/client/package.json/node-fetch/open
> chore(client): bump node-fetch to 2.6.6

- packages/client/src/generators.test.ts
- packages/client/src/generators.ts
- packages/client/src/grant-token.test.ts
- packages/client/src/grant-token.ts
- packages/client/src/index.ts
This PR includes following updates
1. add clientId to the token endpoint
- should passing in `clientId` to the token endpoint
- update the `grantTokenByAuthorizationCode` input params as a single map payload
2. no need to encode the code_verifier
3. rename `generateRandom` method to `generateEncodedRandom` to be more specific
LOG-207
test locally on playground integrated with client
UT case updated
@wangsijie @IceHe cc: @xiaoyijun @gao-sun
> fix(client): fix client sdk

- .gitignore
- packages/playground/README.md
- packages/playground/jest.setup.js
- packages/playground/package.json
- packages/playground/razzle.config.js
- packages/playground/src/App.tsx
- packages/playground/src/LogtoClientContext.ts
- packages/playground/src/consts/url.ts
- packages/playground/src/pages/Callback/index.tsx
- packages/playground/src/pages/Home/index.tsx
- pnpm-lock.yaml
Integrate playground with client js sdk
- Create a logtoClient instance and put is in as a context
- replace original login/logout logic using logtoClient api
- add `jest-setup` file to bypass the `jose` jest env issue
- As `token_set` storage is hidden to the client, display IDToken claims instead of original token_set details  after success login
Test locally successfully sign-in and out
@wangsijie @xiaoyijun cc: @IceHe @gao-sun
> refactor(playground): integrate playground with client js sdk

- packages/client/src/index.test.ts
- packages/client/src/index.ts
Add support for an optional listener on authenticated state change
add test cases in `index.test.ts`
> feat: onAuthStateChange

- packages/client/src/generators.test.ts
- packages/client/src/generators.ts
- packages/client/src/index.ts
- packages/client/src/utils.test.ts
- packages/client/src/utils.ts
Move method `generateScope` from `util.ts` to `generators.ts`
Pass all existing unit tests.
> refactor(js): move generateScope to generators.ts

- packages/client/package.json
- packages/client/webpack.config.js
- packages/playground/package.json
- packages/playground/razzle.config.js
- pnpm-lock.yaml
add webpack bundle analyze script
As we have observed the package oversize issue on clientjs and playground, to better analyze the bundle size and optimize it, add the `webpack-bundle-analyzer`
with script `pnpm report`
> chore(analyze): add webpack bundle analyze script

- packages/client/package.json
- packages/client/src/discover.ts
- packages/client/src/errors.ts
- packages/client/src/grant-token.ts
- packages/client/src/utils.test.ts
- packages/client/src/utils.ts
- pnpm-lock.yaml
as zod package size exceed our limit. replace zod with superstruct
We have observed that `zod` dependency cost lot in terms of the client package's bundle size.  So find an alteration [superstruct](https://github.com/ianstormtaylor/superstruct) to replace the `zod`. Both shares a similar api. Easy to shift. 
Before:
After:
For More details:
https://www.npmtrends.com/yup-vs-zod-vs-superstruct
https://bundlephobia.com/package/superstruct@0.15.3
UT case updated. Test locally on playground 
@wangsijie @gao-sun cc: @IceHe @xiaoyijun
> refactor(client): burn zod dependency

- packages/react/src/auth-state.ts
- packages/react/src/context.tsx
- packages/react/src/provider.tsx
- packages/react/src/reducer.ts
- packages/react/src/use-logto.spec.tsx
- packages/react/src/use-logto.ts
Need a better state management for react SDK, use `useReducer` to manage login flows.
reuse `use-logto.spec.tsx`
> refactor(react): use reducer

- packages/client/src/discover.ts
- packages/client/src/grant-token.ts
- packages/client/src/utils.ts
We have encountered a `superstruct` type thrown error specifying a unmatched type of `OIDCConfig`
According to the `struct` official [document](https://docs.superstructjs.org/api-reference/types) 
replace `object` declaration using [type](https://docs.superstructjs.org/api-reference/types#type)
test locally on playground
@wangsijie cc: @IceHe @xiaoyijun @gao-sun
> fix(client): fix superstruct validation rule

- packages/react/src/provider.tsx
- packages/react/src/reducer.ts
- packages/react/src/use-logto.spec.tsx
use `logtoClient.isLoginCallback` to auto detect if need to handle callback
[LOG-232](https://linear.app/silverhand/issue/LOG-232/react-logincallback-comp)
`use-logto.spec.tsx`
> feat(react): auto handle callback

- packages/react/src/ProtectedRoute.spec.tsx
Since #92 , `isLoginRedirect` will be called automaticly, but is not mocked in `ProtectedRoute.spec.tsx`, causing test failed.
> test(react): mock isLoginRedirect to fix test

- packages/client/src/api.test.ts
- packages/client/src/api.ts
- packages/client/src/discover.ts
- packages/client/src/grant-token.test.ts
- packages/client/src/grant-token.ts
- packages/client/src/index.test.ts
- packages/client/src/index.ts
- packages/client/src/utils.ts
Do 2 things to support running both in node and browser(already supported):
1. can pass in custom `fetchFunction` in constructer
2. onRedirect parameter, defaults to `window.location.assign`
change `testEnvironment` to `node` and run test for file `index.test.ts`
> feat(client): support node

- packages/client/src/index.test.ts
- packages/client/src/index.ts
- packages/client/src/parse-callback.test.ts
- packages/client/src/parse-callback.ts
- packages/client/src/request-login.test.ts
- packages/client/src/request-login.ts
- packages/client/src/session-manager.test.ts
- packages/client/src/session-manager.ts
- packages/client/src/utils.test.ts
- Login with random state value to prevent csrf attacking
- Related notion doc : https://www.notion.so/silverhand/OAuth-2-0-Security-b7b1f43d5c784b599c084d3ff356525c
- Pass all existing tests
- Add necessary test cases for `getLoginUrlAndCodeVerifier` method
- `handleCallback` require correct `state` parameter value in url so updated related unit tests
- `isLoginRedirect` require a `state` parameter value ( but do not need to confirm its correctness ) in url so updated related unit tests
- **Testing on js/playground**
1. loginWithRedirect : 
i. generate state
ii. save state
2. handleCallback : get and check state
3. succeed to login
> feat(js): add state value to prevent csrf attacking

- packages/client/src/utils.ts
fix the problem:
a possible reason is that returning `window.location.assign` directly will lose context
[https://stackoverflow.com/questions/10743596/why-are-certain-function-calls-termed-illegal-invocations-in-javascript](https://stackoverflow.com/questions/10743596/why-are-certain-function-calls-termed-illegal-invocations-in-javascript)
> fix(client): wrap window.location.assign

- packages/client/src/index.test.ts
- packages/client/src/index.ts
- Replace whitespaces in `tokenSetCacheKey` via `encodeURI` method
- Fix related unit tests.
Pass all existing unit tests.
> refactor(client): replace whitespaces in tokenSetCacheKey

- packages/client/src/modules/errors.ts
- The property `uri` is unnecessary in LogtoError now.
- Reference: https://www.notion.so/silverhand/Error-Handling-Conventions-fc4b89a0d3bb456699da61dd8f3f997f
Passing all existing tests
> chore(client): remove useless uri property in LogtoError

- .github/workflows/main.yml
- .gitignore
- codecov.yml
- packages/client/jest.config.js
- packages/client/package.json
- packages/playground/package.json
- packages/playground/razzle.config.js
- packages/react-playground/package.json
- packages/react-playground/razzle.config.js
- packages/react/jest.config.js
- packages/react/package.json
Add test coverage scripts and actions, with coverage threshold set to 80%.
- client
- react
- playground
- react-playground
script: `pnpm test:coverage`
reportpath: `/coverage`
test locally
@logto-io/eng
> test: add test coverage scripts and actions

- .github/workflows/main.yml
- codecov.yml
- packages/client/jest.config.js
- packages/client/package.json
- packages/playground/package.json
- packages/playground/razzle.config.js
- packages/react-playground/package.json
- packages/react-playground/razzle.config.js
- packages/react/jest.config.js
- packages/react/package.json
- pnpm-lock.yaml
Update the [codecov](https://docs.codecov.com/docs/pull-request-comments#disable-comment) settings:
1.  Add monorepo project flags
2.  Config the GitHub actions run `codecov` uploader internally using node uploader 
3. remove the auto comment feature of `codecov` bot, using `codecov` team config instead
> the node [uploader](https://github.com/codecov/codecov-node)  is marked as deprecated. However, their new version of the[ opensource uploader](The new uploader is open source) is WIP. need to migrate later. 
Test should reflected on this PR ci 
@logto-io/eng
> ci: add codecov report ci task

- packages/js/jest.config.js
- packages/js/package.json
- packages/js/src/utils/errors.ts
- packages/js/src/utils/id-token.test.ts
- packages/js/src/utils/id-token.ts
- packages/js/tsconfig.json
- pnpm-lock.yaml
- Add `LogtoErrorCode.idToken.invalidToken`
- Make decodeIdToken throw `LogtoErrorCode.idToken.invalidToken` when needed
- Simplify `LogtoErrorCode.idToken.verification.invalidIat` to `LogtoErrorCode.idToken.invalidIat`
- Add development dependency `jest-matcher-specific-error` for matching specific error
LOG-1382
LOG-1355
---
@logto-io/eng
> chore(js): add LogtoErrorCode.idToken.invalidToken and jest-matcher-specific-error

- packages/js/src/utils/errors.ts
- packages/js/src/utils/requester.node.test.ts
- packages/js/src/utils/requester.test.ts
- packages/js/src/utils/requester.ts
- Add Requester for `fetch` Response
- [`fetchOidcConfig`](https://www.notion.so/silverhand/fetchOidcConfig-887d329a10de43b5acc2f279c04dba4b) requires `Requester` to fetch data.
- Reference: [packages/client/src/api/discover.ts](https://github.com/logto-io/js/blob/master/packages/client/src/api/discover.ts)
- The developers should provide his/her `Requester` (`fetch` function) under Node.js environments according to the code implemented by @wangsijie before.
- Reference: [packages/client/src/utils/requester.ts](https://github.com/logto-io/js/blob/master/packages/client/src/utils/requester.ts)
LOG-766 → LOG-1421
---
@logto-io/eng
> feat(js): requester

- packages/js/src/include.d/dom.d.ts
- packages/js/src/utils/callback-uri.test.ts
- packages/js/src/utils/callback-uri.ts
- packages/js/src/utils/errors.test.ts
- packages/js/src/utils/errors.ts
- packages/js/src/utils/requester.test.ts
- packages/js/src/utils/requester.ts
- Refactor `LogtoError`
- Add LogtoRequestError and refactor requester
- Throw LogtoRequestError when the request fails due to Logto core server.
LOG-1422
---
@logto-io/eng
> refactor(js): refactor requester and LogtoError, add LogtoRequestError

- packages/js/src/core/fetch-token.test.ts
- packages/js/src/core/fetch-token.ts
- simplify fetchTokenByRefreshToken with camelcaseKeys
- remove useless superstruct.assert in fetchTokenByRefreshToken
LOG-782
---
@logto-io/eng
> feat(js): refactor fetchTokenByRefreshToken

- packages/js/package.json
Override eslint config in project `logto-io/js` to allow 6 function parameters at maximum
> chore(js): override eslint config to allow 6 params at max

- packages/browser/jest.config.js
- packages/browser/package.json
- packages/browser/src/index.test.ts
- packages/browser/src/index.ts
- packages/browser/tsconfig.json
- packages/browser/webpack.config.js
- packages/js/package.json
- pnpm-lock.yaml
- [refactor(browser): initialize js/browser package](https://github.com/logto-io/js/commit/151fdd748a02e8758ea7e323596ca10953d24748)
- [chore(js): remove redundent part of eslintConfig.extends](https://github.com/logto-io/js/pull/157/commits/10a7bda5d59042757bbb3e78c081972787c4ab4a) 
From
```json
"eslintConfig": {
"extends": "@silverhand/eslint-config"
```
to
```json
"eslintConfig": {
"extends": "@silverhand"
```
---
Deprecated previous #156 due to the wrong branch name.
LOG-1466
Just add a temp test for passing CI.
---
@logto-io/eng
> refactor(browser): initialize js/browser package

- packages/js/package.json
Revert the changes made in #155 as we decided to use the object pattern in the end.
Thus, remove the override of eslint rule of `max-params` in js project
No need
> chore(js): remove eslint override of max-params

- packages/js/src/core/fetch-token.test.ts
- packages/js/src/core/fetch-token.ts
- [refactor(js): rename scope to scopes in fetchTokenByRefreshToken and fix scope type](https://github.com/logto-io/js/pull/164/commits/3c7e8f6245f4bc59794907d89e169ed2aada9358)
- [chore(js): make RefreshTokenTokenResponse.idToken optional](https://github.com/logto-io/js/pull/164/commits/741cdfecbc3a3023a9e29032d98b3003dd59f1c4)
Summary:
- function parameter: `scopes: string[]`
- function response: `scope: string`
- /oidc/token api parameter: `scope: string`
- /oidc/token api response: `scope: string`
Related:  LOG-771
---
@logto-io/eng
> refactor(js): rename scope to scopes in fetchTokenByRefreshToken

- packages/browser/jest.config.js
- packages/browser/package.json
- packages/browser/src/errors.ts
- packages/browser/src/index.test.ts
- packages/browser/src/index.ts
- packages/browser/tsconfig.json
- pnpm-lock.yaml
feat(browser): sign-in session storage
Related #170 
LOG-1544
LOG-790
LOG-882
---
@logto-io/eng
> feat(browser): sign-in session storage

- packages/js/src/core/fetch-token.test.ts
- packages/js/src/core/fetch-token.ts
feat(js): add CodeTokenResponse ( which is missing in #165 )
---
The core difference between `CodeTokenResponse` and `RefreshTokenTokenResponse` is `idToken`.
- `CodeTokenResponse.idToken` is required.
- `RefreshTokenTokenResponse.idToken` is optional.
LOG-770
---
@logto-io/eng
> feat(js): add CodeTokenResponse

- packages/browser/src/index.test.ts
- packages/browser/src/index.ts
refactor(browser): make requester an optional LogtoClient constructor parameter
Make LogtoClient easier to use: the developer does not need to create Requester his/herself.
LOG-1575
---
@logto-io/eng
> refactor(browser): make requester an optional LogtoClient constructor parameter

- packages/browser/package.json
- packages/browser/src/index.ts
- packages/js/package.json
- pnpm-lock.yaml
Main:
- [chore(browser): make necessary LogtoClient properties nullable](https://github.com/logto-io/js/commit/a971af4e13391c01747c5d504b8da36fa09969cb)
- [chore(js,browser): upgrade @silverhand/essentials to version 1.1.6](https://github.com/logto-io/js/commit/6aae68d478607227c37a89714dbf0fa5ad17b415)
Others:
- [chore(browser): fix grammatical error in the comment](https://github.com/logto-io/js/pull/189/commits/d47fb5602f6833f7795334aa17a4c808b43491d4)
---
Because `idToken` and `refreshToken` can be retrieved from `localStroage` via `getItem(key): string | null`, 
better define related properties as type `Nullable<string>` (i.e. `string | null`).
LOG-1576
---
@logto-io/eng
> chore(browser): make necessary LogtoClient properties nullable

- packages/browser/src/index.ts
- fix(browser): getAccessToken saves refreshToken and idToken
- Bug: forget to save refreshToken and idToken in the related object properties.
LOG-1147
(The tests will be added in LOG-1572 later.)
---
@logto-io/eng
> fix(browser): getAccessToken saves refreshToken and idToken

- packages/js/src/consts/index.ts
- packages/js/src/core/sign-in.test.ts
- packages/js/src/core/sign-in.ts
Fix incorrect `response_type` used in js SDK. Should use `code` instead of `authorization_code`
Passed all test cases.
> fix(js): response_type should be hard-coded as 'code'

- packages/js/src/consts/index.ts
Fix incorrect `grant_type` usage in js SDK. The value of enum `GrantType.Authorization` should be `authorization_code` instead of `code`
> fix(js): grant type should be 'authorization_code'  instead of 'code'

- packages/browser/src/index.ts
Export two js core types from browser SDK
* IdTokenClaims
* UserInfoResponse
The exported types will be used in the upcoming React SDK.
> feat(browser): export js core types from browser SDK

- packages/browser/src/index.test.ts
- packages/browser/src/index.ts
`fetchUserInfo` function should use `userinfo_endpoint` instead of `authorization_endpoint`. This PR addresses the issue.
[LOG-1853](https://linear.app/silverhand/issue/LOG-1853/fix-wrong-endpoint-used-in-fetchuserinfo-in-browser-sdk)
> fix(browser): should use userinfo_endpoint in fetchUserInfo function

- packages/react/src/hooks/index.test.tsx
- packages/react/src/hooks/index.ts
Remove handleSignInCallback method from useLogto export in React SDK, for it's automatically called in the SDK itself once the sign-in is redirected
[LOG-1859](https://linear.app/silverhand/issue/LOG-1859/remove-handlesignincallback-from-uselogto-export)
> refactor(react): remove handleSignInCallback export from useLogto hook

- packages/browser/src/index.ts
Improve `isSignInRedirected` logic in browser SDK. Instead of using `startWith`, we should use strict check on the redirect URL, the origin and pathname must be exactly matched. 
[LOG-1860](https://linear.app/silverhand/issue/LOG-1860/improve-issigninredirected-logic-in-browser-sdk)
> refactor(browser): use strict check logic in isSignInRedirected function

- packages/browser/package.json
- packages/js/package.json
- packages/react/package.json
it's deprecated
https://docs.npmjs.com/cli/v8/using-npm/scripts#life-cycle-scripts
> fix: remove `prepublish` script

- packages/browser/package.json
- packages/js/package.json
- packages/react/package.json
MPL 2.0 is too large and it's ok to use MIT for SDKs
N/A
> chore: change license to MIT

- packages/react-sample/src/pages/Callback/index.tsx
- packages/react/src/context.tsx
- packages/react/src/hooks/index.test.tsx
- packages/react/src/hooks/index.ts
- packages/react/src/index.ts
- packages/react/src/provider.tsx
Improve hooks in React SDK, by extracting `handleSignInCallback` logic from the main `useLogto` hook, in order to avoid issues caused by multiple useEffect executions.
[LOG-1905](https://linear.app/silverhand/issue/LOG-1905/refactor-react-sdk-hooks)
> refactor(react): improve hooks in react sdk

- package.json
- packages/browser/package.json
- packages/js/package.json
- packages/react/package.json
v0.1.4 [publish failed](https://github.com/logto-io/js/runs/5598155552?check_suite_focus=true) since `@logto/js` didn't change nor build while `@logto/browser` is its dependent.
this PR leverages root `prepack` lifecycle to prevent publish failure.
see [Lifecycle Scripts](https://github.com/lerna/lerna/tree/v4.0.0/commands/publish#lifecycle-scripts) for detailed explanantion.
see https://github.com/lerna/lerna/issues/2211#issuecomment-592703853
LOG-1973
modify something in `@logto/browser`, run `pnpm prepack` now builds `@logto/js`.
> fix: leverage root `prepack` lifecycle for publish

- packages/browser-sample/src/consts.js
- packages/browser-sample/src/index.js
- packages/browser/src/index.test.ts
- packages/browser/src/index.ts
- packages/browser/src/utils/index.test.ts
- packages/react-sample/src/App.tsx
- packages/react-sample/src/consts/index.ts
- packages/react/src/hooks/index.test.tsx
Rename `clientId` to `appId` in JS SDKs
[LOG-2252](https://linear.app/silverhand/issue/LOG-2252/rename-client-id-to-app-id-in-sdks)
> refactor(js): rename clientId to appId in js SDKs

- packages/browser/src/index.ts
Read/write refreshToken from localStorage only, instead of loading from browser memory object.
This fix aims to prevent using an expired refreshToken when more application tabs are open. Since we have the refreshToken rotations enabled, refreshToken will expire immediately after it is used to exchange for the accessToken.
[LOG-2328](https://linear.app/silverhand/issue/LOG-2328/always-getset-refresh-token-from-local-storage)
> fix(browser): read/write refreshToken from/to localStorage only

- packages/browser/src/index.test.ts
- packages/browser/src/index.ts
Remove sign-in session item from sessionStorage after a succesful sign-in
[LOG-2330](https://linear.app/silverhand/issue/LOG-2330/clear-session-after-sign-in)
> fix(browser): remove session item after successful sign-in

- packages/react-sample/src/pages/Callback/index.tsx
- packages/react/src/hooks/index.ts
Try simplify the callback logics in user apps. Now `useHandleSignInCallback` hook will accept a return URL param, and will navigate the browser to that URL once the sign-in callback process is completed successfully.
> refactor(react): simplify callback logic in sample app

- packages/react/src/context.tsx
- packages/react/src/hooks/index.test.tsx
- packages/react/src/hooks/index.ts
- packages/react/src/provider.tsx
Add `error` prop to `useLogto` hook context.
[LOG-1927](https://linear.app/silverhand/issue/LOG-1927/add-error-prop-to-uselogto-context)
> feat(react): add error prop to useLogto context

- packages/browser/src/index.ts
Remove `idToken` and `refreshToken` from localStorage before navigating to sign-in page, in order to clear the authenticated status in application.
This is helpful when session is expired and user would need to re-sign-in to the app. Restoring these two token would help provider a cleaner environment in the re-signing-in process.
> fix(browser): clear authenticated status before signing-in

- packages/browser-sample/package.json
- pnpm-lock.yaml
As discussed offline with @gao-sun , add typescript to devDependencies of browser-sample project, in order to get rid of the annoying warnings from eslint-configs.
> fix(browser-sample): add typescript to browser-sample dev dependencies

- packages/react/src/hooks/index.ts
Move statements to try blocks as much as possible.
Fixed an infinite loop issue caused by executing `window.location.assign` even on error occurred, which can be avoided by moving these staments into try blocks.
[LOG-2600](https://linear.app/silverhand/issue/LOG-2600/move-locationassign-to-try-block-in-react-sdk)
> refactor(react): move statements to try blocks

- packages/react/src/hooks/index.ts
- packages/react/src/index.ts
- packages/vue/src/index.test.ts
- packages/vue/src/index.ts
* Export `LogtoClientError` and `LogtoClientErrorCode` from all js SDKs
* Return `error` object from `useHandleSignInCallback` hook
> refactor: export LogtoClientError from SDKs

- packages/react/src/index.ts
- packages/vue/src/index.ts
Fix an issue in React and Vue SDKs.
The exported `LogtoClientError` should be a class not a type.
> fix: should export 'LogtoClientError' as a class instead of a type

- packages/browser/src/index.ts
- packages/js/src/utils/errors.ts
- packages/react/src/index.ts
- packages/vue/src/index.ts
Previously, in our LogtoError class, there is a `data` property and its type is `unknown`, which makes the it difficult for any client that integrated our SDK to load content in `error.data`. The user will have to write a lousy type guard in order to make it work.
Therefore, we provide a new `OidcError` class from our core SDK, and export it in all js SDKs, in order to make it possible to write:
```ts
if (error.data instanceof OidcError) {
const { error, errorDesccription } = error.data;
...
}
```
> refactor: expose OidcError class from SDKs

- packages/js/src/utils/errors.ts
`errorDescription` in OidcError should be optional string, according to OIDC provider definitions.
N/A
> fix(js): oidc error description should be optional string

- packages/js/src/utils/callback-uri.test.ts
- packages/js/src/utils/callback-uri.ts
- packages/js/src/utils/errors.test.ts
* Improved error data type handling in callback URI verification. Now use `OidcError` class instead of plain `Object`.
* Added unit test case
> refactor(js): improve error data type in callback URI verification

- packages/react/src/hooks/index.ts
- packages/vue/src/context.ts
Use 'console.error' to output all caught errors in browser debugger console in React and Vue SDKs. So that the user can quickly navigate to the code line where the error is thrown.
> refactor: use `console.error` to output all caught errors in debugger console

- packages/react/src/hooks/index.ts
- packages/vue/src/plugin.ts
Removed `setIsAuthenticated(false)` from `signOut` method in React and Vue SDKs, for it will cause an immediate state change in the client app, which might lead to problems that prevent browser navigating to the end session endpoint.
> refactor: remove setIsAuthenticated false from sign out

- packages/react/src/hooks/index.ts
- packages/vue/src/plugin.ts
Remove `setIsAuthenticated(true)` from `handleSignInCallback` method.
> refactor: remove setIsAuthenticated true from handleSignInCallback

- packages/browser/src/index.ts
- packages/js/src/core/sign-in.test.ts
- packages/js/src/utils/scopes.test.ts
- packages/js/src/utils/scopes.ts
Add 'profile' to reserved scopes in js sdk
> refactor: add 'profile' to reserved scopes in js sdk

- packages/react-sample/src/pages/Callback/index.tsx
- packages/react/src/hooks/index.ts
- packages/vue-sample/src/views/CallbackView.vue
- packages/vue/src/index.ts
- packages/vue/src/plugin.ts
Refactor `useHandleSignInCallback` hook method in React and Vue SDKs.
* Pass in a `callback` function instead of a `returnToPageUrl`
* Set `isAuthenticated` to true immediately after successfully handling the sign in callback
* Execute the `callback` method after successfully handling the sign in callback, instead of navigating the page using `window.location.assign`
> refactor: add callback function param to useHandleSignInCallback hook

- packages/browser/src/index.test.ts
- packages/browser/src/index.ts
- Append the reserved scopes to the custom ones in `LogtoClient` constructor.
- See Slack thread [discussion](https://silverhand-io.slack.com/archives/C02A8G4HVAM/p1655098928722249)
- Remove the parameter `scopes` when `getAccessTokenByRefreshToken`, that aligns with Kotlin and Swift SDK for now
- Next up: LOG-1464 @simeng-li will deal with the required scopes when `getAccessTokenByRefreshToken`. See Slack thread [discussion](https://silverhand-io.slack.com/archives/C02A8G4HVAM/p1655099458314629)
LOG-3006
UTs.
> feat(browser): only append reserved scopes in LogtoClient constructor

- packages/browser-sample/package.json
- packages/browser/package.json
- packages/js/package.json
- packages/react-sample/package.json
- packages/react/package.json
- packages/vue-sample/package.json
- packages/vue/package.json
Remove `npx only-allow pnpm` from all sub-packages, leaving it only in the root package.json of our monorepo.
[LOG-3040](https://linear.app/silverhand/issue/LOG-3040/support-npm-i-for-logto-js-sdks)
N/A
> chore: remove only-allow pnpm from all sub-packages

- packages/js/src/utils/id-token.ts
Add userinfo props to id token claims type, since we already have these values in idTokenClaims.
The client app can decode userinfo from idTokenClaims without requesting from the `/oidc/me` interface
N/A
> refactor(js): add userinfo props to id token claims type

- packages/browser/src/index.ts
getAccessTokenByRefreshToken should not return idToken. Pur our offline discussion, always pass the `offline_access` scope in.
test locally
@logto-io/eng
> fix(js SDK): getAccessTokenByRefreshToken should not return idToken

- packages/browser/src/index.ts
Refresh access token without a resource should return id token. Only if the resource is provided, hard code the scope as `offline_access`.
@logto-io/eng
> fix(js): refresh access token without a resource should return id token

- packages/browser/src/index.test.ts
- packages/browser/src/index.ts
- packages/js/src/consts/index.ts
- packages/js/src/core/fetch-token.ts
- packages/js/src/core/sign-in.test.ts
- packages/js/src/core/sign-in.ts
`prompt` value can be configurable on our SDK.
To change the refresh token in the `CodeTokenResponse` to be optional for we won't get a refresh token from it if the prompt value is `login`. See Slack thread [discussion](https://silverhand-io.slack.com/archives/C02A8G4HVAM/p1649906832335309)
LOG-2936
> feat(js,browser): configurable prompt

- packages/browser/src/index.test.ts
- packages/browser/src/index.ts
Should use user specified prompt type in logtoClient when calling `.signIn()` method
> fix(browser): should use prompt param on sign-in

- packages/react/src/hooks/index.ts
- packages/vue/src/index.ts
- packages/vue/src/plugin.ts
`postLogoutRedirectUri` should be optional param. Fixed in React and Vue SDKs
> refactor: postLogoutRedirectUri should be optional param

- packages/next-sample/pages/api/sign-out.ts
- packages/next-sample/tsconfig.json
- packages/next/src/index.test.ts
- packages/next/src/index.ts
Add sign out route handler.
UTs and sample(local tested)
> feat(next): sign out

- packages/client/src/index.test.ts
- packages/client/src/index.ts
- packages/client/src/mock.ts
- packages/client/src/types/index.ts
- packages/next/src/index.ts
Add an optional feature: persist access token to storage.
Before this, access token is only saved in instance property, when creating a new instance, it doesn't have any access token, but it can reuse refresh token from storage, and then grant a new access token. This is fine for SPA, since it only have an instance when the user navigates between pages. But in other circumstances, especially in traditional app when LogtoClient is run in server side, it will create a new instance each time when receiving a request, that means there will be so many instances sharing the same storage. Then, it'll be good to reuse access token.
UTs.
> feat(client): persist access token

- packages/next/src/index.test.ts
- packages/next/src/index.ts
- packages/next/src/storage.ts
Implement expiration policy:
1. set cookie's max-age to the same as refresh token
2. if the access token is valid, the session is authenticated
3. if the access token is expired, try to grant new with refresh token
Local tested with sample code.
> feat(next): grant access token and check expiration

- packages/next/src/index.test.ts
- packages/next/src/index.ts
- packages/next/src/types.ts
For checking isAuthenticated, there are 2 steps:
1. check `logtoClient.isAuthenticated`, that actually means that `idToken` is exist (session is exist).
2. try to get an accessToken, make sure the refresh token is still valid.
step 2 is optional and skiped by default.
UTs and local tested with sample.
> feat(next): set getAccessToken as an option

- packages/next-sample/pages/api/logto/[action].ts
- packages/next-sample/pages/api/sign-in-callback.ts
- packages/next-sample/pages/api/sign-in.ts
- packages/next-sample/pages/api/sign-out.ts
- packages/next-sample/pages/api/user.ts
- packages/next-sample/pages/index.tsx
- packages/next-sample/pages/profile-ssr.tsx
- packages/next-sample/pages/protected.tsx
- packages/next/src/index.test.ts
- packages/next/src/index.ts
Add method `handleAuthRoutes`: handle 4 routes together.
UTs.
> feat(next): handleAuthRoutes

- packages/client/src/utils/requester.test.ts
- packages/client/src/utils/requester.ts
- packages/js/src/utils/errors.test.ts
- packages/js/src/utils/errors.ts
- Add `logtoRequestErrorSchema` to check Logto request error
- Refactor `createRequester`
- Throw Logto request error when the response contains both `code` and `message`
- Otherwise, throw Logto error with the message `Unexpected response error from the server.`
Original
Now
> refactor(js,client): createRequester

- packages/express/src/index.test.ts
- packages/express/src/index.ts
- packages/express/src/types.ts
- packages/next-sample/pages/index.tsx
- packages/next-sample/pages/profile-ssr.tsx
- packages/next/src/index.test.ts
- packages/next/src/index.ts
- packages/next/src/types.ts
- packages/node/src/index.test.ts
- packages/node/src/index.ts
- packages/node/src/types.ts
Implement the middleware: withLogto.
And extract "getLogtoUserFromRequest" from Next.js SDK to Node.js SDK to share with express.
UTs
> feat(express): with logto

- packages/browser/src/storage.test.ts
- packages/browser/src/storage.ts
- packages/client/src/adapter.ts
- packages/client/src/index.test.ts
- packages/client/src/index.ts
- packages/client/src/mock.ts
- packages/express-sample/package.json
- packages/express/src/storage.test.ts
- packages/express/src/storage.ts
- packages/next/src/storage.test.ts
- packages/next/src/storage.ts
- packages/node/src/index.test.ts
- packages/node/src/index.ts
- packages/react-sample/src/pages/Home/index.tsx
- packages/react/src/hooks/index.test.tsx
- packages/react/src/hooks/index.ts
- packages/react/src/provider.tsx
- packages/vue-sample/src/views/HomeView.vue
- packages/vue/src/context.ts
- packages/vue/src/index.test.ts
- packages/vue/src/index.ts
- packages/vue/src/plugin.ts
- pnpm-lock.yaml
Since React Native storage solutions are all async and we need to write React Native SDK to extend from @logto/client , it is required to implement the Storage interface in React Native.
However, the existing functions (getItem, setItem, removeItem) in Storage interface are all synchronous, we can't implement the interface with an asynchronous storage solution.
Therefore, we need to make storage functions async in @logto/client in order to unblock React Native SDK development.
> refactor: make storage functions async

- packages/react/src/hooks/index.ts
- packages/vue/src/plugin.ts
Remove `setLoadingState(false)` after calling `signIn()` from React and Vue SDKs, in order to remove a potential infinite loop and sign-in failure.
> fix(react,vue): do not set loading to false after calling signIn

- packages/browser/package.json
- packages/browser/src/utils/generators.test.ts
- packages/client/package.json
- packages/js/package.json
- packages/js/src/utils/id-token.test.ts
- packages/js/src/utils/id-token.ts
- packages/node/package.json
- packages/node/src/utils/generators.test.ts
- packages/react/package.json
- pnpm-lock.yaml
Bump @silverhand/essentials toolkit to v1.2.1 to use utf-8 character set when encoding and decoding base64 strings, in order to avoid ending up with garbled text with CJK characters
> fix: bump to essentials v1.2.1 to use utf-8 on decoding base64

- packages/browser-sample/src/index.js
- packages/browser/src/index.ts
- packages/client/package.json
- packages/client/src/index.ts
- packages/express/src/index.ts
- packages/js/package.json
- packages/js/src/core/sign-in.test.ts
- packages/js/src/core/sign-in.ts
- packages/js/src/utils/id-token.ts
- packages/js/src/utils/scopes.test.ts
- packages/js/src/utils/scopes.ts
- packages/next/src/index.ts
- packages/node/src/index.ts
- packages/react-sample/src/App.tsx
- packages/react/src/index.ts
- packages/vue-sample/src/main.ts
- packages/vue/src/index.ts
- pnpm-lock.yaml
* JS SDKs export `ReservedScope` and `UserScope` from @logto/core-kit
* By default, the SDK provides `openid`, `offline_access` and `profile` scopes
* Update the type definition of `IdTokenClaim`, change "avatar" to "picture", and add email and phone_number properties
> chore: update default scopes and IdTokenClaim definition

- packages/express-sample/src/app.ts
- packages/express/src/index.ts
- packages/express/src/types.ts
- packages/next-sample/pages/api/logto/user-info.ts
- packages/next-sample/pages/index.tsx
- packages/next/src/index.ts
- packages/next/src/types.ts
- packages/node/src/index.test.ts
- packages/node/src/index.ts
- packages/node/src/types.ts
Add config "fetchUserInfo" to `express` and `next`, enable user info endpoint in Node.js SDK family.
Local tested with express-sample and next-sample.
> feat(express,next,node): support fetchUserInfo

- packages/remix/src/useCases/handleSignOut/HandleSignOutController.ts
There was a problem with the `sign-out` in the Remix SDK where after performing the `sign-out`, the user was able to perform a `sign-in` without executing the actual authentication flow:
[Screen_recording_2022-10-19_23.50.18.webm](https://user-images.githubusercontent.com/224910/196992055-8f067240-cd0a-4da5-b090-9bccd170ea46.webm)
You can use the example app which currently lives in this [repo](https://github.com/openformation/logto-remix/tree/main/example).
> fix(remix): use the correct sign-out redirect URL 

- packages/client/src/index.test.ts
- packages/client/src/index.ts
Fixed a bug that `accessToken` is still in local storage after successfully signing out.
Updated test case to reflect this change.
> fix(client): remove access token from storage after sign-out

- packages/client/src/index.test.ts
- packages/client/src/index.ts
remove refresh token concurrent request protection. For now, we protect it on the server side.
reference: https://github.com/logto-io/kotlin/pull/203
UTs
> refactor(client): remove refresh token concurrent request protection

- packages/browser-sample/package.json
- packages/browser/package.json
- packages/client/package.json
- packages/express-sample/package.json
- packages/express/package.json
- packages/js/package.json
- packages/next-sample/package.json
- packages/next/package.json
- packages/node/package.json
- packages/react-sample/package.json
- packages/react/package.json
- packages/remix/package.json
- packages/vue-sample/package.json
- packages/vue/package.json
- pnpm-lock.yaml
- Add one last step to the build script to copy the type declaration for matching the `.mjs` file.
- TypeScript needs a `.mts` file in the dependency to correctly import types when "moduleResolution" is "nodenext".
- https://github.com/microsoft/TypeScript/issues/47848 https://github.com/microsoft/TypeScript/issues/49189
- Lock workspace dependency versions.
tested in core, both ESM and CJS typing/building work as expected
> chore: update `package.json`

- packages/next/README.md
Signed-off-by: tison <wander4096@gmail.com>
Fix broken links in README.
Manually verify the links work now.
> fix: links in README

- packages/client/src/index.ts
Remove the parameter `scope` for `getAccessTokenByRefreshToken`. Then the OP server will automaticly attach all the available scopes (in refresh token) to this access token.
Local tested
> feat(client): remove scope for access token grant

- packages/js/src/core/user-info.ts
Fix `UserInfoResponse` type in JS SDKs. Make most of the fields `Nullable`, which reflects the real field type in DB
OR
> chore: add nullable to UserInfoResponse type properties

- packages/browser/src/index.ts
- packages/client/src/index.test.ts
- packages/client/src/index.ts
- packages/client/src/mock.ts
- packages/express/src/index.test.ts
- packages/express/src/index.ts
- packages/js/src/consts/index.ts
- packages/js/src/core/sign-in.test.ts
- packages/js/src/core/sign-in.ts
- packages/js/src/types/index.ts
- packages/next/src/index.test.ts
- packages/next/src/index.ts
- packages/node/src/index.ts
- packages/react-sample/src/pages/Home/index.module.scss
- packages/react-sample/src/pages/Home/index.tsx
- packages/react/src/hooks/index.ts
- packages/react/src/index.ts
- packages/vue/src/index.ts
- packages/vue/src/plugin.ts
Add `interaction mode` props to the signIn handler to support a sign-up first user experience. Related [core updates](https://github.com/logto-io/logto/pull/3280).
- signUp: specify a sign-up first interaction flow
- signIn or undefined: default sign-in interaction flow
Updated SDK:
test react-sample
OR
> feat(js): add interactionMode props to signIn method

- packages/next-sample/pages/index.tsx
According to [NextJs official doc](https://nextjs.org/docs/api-reference/next/link), client-side transitions between routes can be enabled via the `Link` component.
In this case, "sign in" is not an internal route, it'll cause CORS issue because NextJS will perform some "pre-render".
Use `location.assign` instead.
Local tested.
OR
> fix(next-sample): use location assign for sign in redirect

- packages/client/src/index.ts
Remove "idToken" check for "sign out":
The problem is that, if the "idToken" is already expired, the sign out process will fail, then the user is not able to sign out and sign in again.
Local tested.
OR
> fix: remove id token check for sign out

- packages/browser/FixJsdomEnvironment.ts
- packages/browser/jest.config.ts
- packages/browser/jest.setup.js
- packages/browser/package.json
- packages/browser/tsconfig.json
- packages/react/src/hooks/index.test.tsx
- packages/react/src/hooks/index.ts
- pnpm-lock.yaml
if we don't check `isLoading` when calling sign-in callback, it may cause duplicate calls and result a global error
tested locally in console, only one token request will be called for `authorization_code` grant
> fix(react): only call handleSignInCallback when not loading

- .changeset/small-eyes-flow.md
- packages/vue/src/index.test.ts
- packages/vue/src/index.ts
We identified an issue with `handleSignInCallback` in React SDK, which causes a sign-in failure due to multiple callback calls within a short period of time. This issue might also exist in Vue SDK, hence this PR is trying to fix it.
- UT passed
- Tested sign-in and sign-out flows in Vue sample, still works properly
> fix(vue): prevent potential issue from handling sign-in callback

- .changeset/violet-dryers-fetch.md
- .github/workflows/publish.yml
- packages/browser/package.json
- packages/client/package.json
- packages/express/package.json
- packages/js/package.json
- packages/next/package.json
- packages/node/package.json
- packages/react/package.json
- packages/remix/package.json
- packages/vue/package.json
- add build in `prepack` script and remove build phase in publish workflow since pnpm will smartly detect and publish in the dependency order thus there is no need for manually build anymore
- force bump `@logto/js` version since the last version has no `lib` (didn't build in either `prepack` nor publish workflow)
- run `pnpm prepack` locally, the script running process is in the dependency order and parallel executing will work when possible.
- bump all sdk versions, dry run publish, work also as expected
> fix: prepack script

- packages/express/package.json
- packages/next/package.json
- packages/node/package.json
CJS sanity checks need to perform after the package is built. So move them to `postpack`.
Local tested
OR
> fix: fix prepack command for module package

- .changeset/slow-cooks-destroy.md
- packages/js/src/utils/access-token.test.ts
- packages/js/src/utils/access-token.ts
- packages/js/src/utils/errors.ts
skip access token decode for opaque token, opaque token has "empty claims", should not throw an error.
Local tested with express sample
OR
> fix: skip access token decode for opaque token

- .changeset/new-adults-happen.md
- package.json
- packages/react/src/hooks/index.test.tsx
- packages/react/src/hooks/index.ts
- packages/vue/src/index.test.ts
- packages/vue/src/index.ts
Fix a potential infinite loop when `handleSignInCallback` fails in some edge cases. Initially reported in #501 
fixes #501 
Unit tested added
> fix(react,vue): potential infinite loop when handleSignInCallback fails

- packages/next/package.json
fix Cannot find module '@logto/next/edge' or its corresponding type declarations.ts (2307) (fixes #499)
Set `typesVersions` to ensure that the corresponding imported type declaration file is used correctly
ref:
https://github.com/vercel/satori/blob/341bfab3326da507accc550d0197ffed90d8e3ac/package.json
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#version-selection-with-typesversions
OR
> fix: add typeVersions field in package.json of Next SDK (#499)

- .changeset/cyan-apples-fold.md
- packages/client/src/index.ts
Calculate the `expiresAt` by `requestedAt + expiresIn`, which ensures the calculated result is always smaller than the actual `exp` property in token claims.
```
expiresAt = requestedAt + actual request time + expiresIn
```
Should fix #518 
N/A
> fix(client): use timestamp before issue token request to ensure expiresAt is smaller than token exp

- packages/react-sample/src/pages/Home/index.tsx
Remove unnecessary dependency from useEffect, since `setState` methods aren't required to be listed as dependencies.
N/A
> chore(react-sample): remove unnecessary useEffect dependency

- .changeset/lazy-steaks-judge.md
- .changeset/mighty-plums-remain.md
- packages/browser/README.md
- packages/browser/src/index.ts
- packages/capacitor/CHANGELOG.md
- packages/capacitor/FixJsdomEnvironment.js
- packages/capacitor/README.md
- packages/capacitor/jest.config.js
- packages/capacitor/jest.setup.js
- packages/capacitor/package.json
- packages/capacitor/rollup.config.js
- packages/capacitor/src/index.test.ts
- packages/capacitor/src/index.ts
- packages/capacitor/tsconfig.build.json
- packages/capacitor/tsconfig.json
- packages/client/src/errors.ts
- packages/client/src/index.ts
- pnpm-lock.yaml
add capacitor sdk for dev convenience.
tested locally with iOS simulator, sign-in/out/storage
> feat: capacitor sdk

- packages/next/edge/index.ts
- packages/next/package.json
- packages/next/src/client.ts
- packages/next/src/index.test.ts
- packages/next/src/index.ts
- packages/next/src/session.test.ts
- packages/next/src/session.ts
- packages/next/src/storage.test.ts
- packages/next/src/storage.ts
- packages/next/src/types.ts
- packages/node/edge/index.ts
- packages/node/src/index.ts
- pnpm-lock.yaml
Remove "iron session" dependency in Next.js SDK, replaced with our own implementation of cookie-based session.
The reason is that, "iron session" depends on `Request` and `Response`, which is not available in Next.js's Server Actions. Next, we'll add support for Server Actions.
Pass existing tests, and tested locally with real Logto endpoint.
> refactor(next): remove iron session

- packages/client/src/index.ts
The current doc comments are a bit misleading as to what value should be passed in as the `callbackUri` param.
Be explicit about the fact that it needs to be the full URI, including search params, and give `window.location.href` as an example of the value one might want to pass in.
I didn't, it's only a doc comment change
OR
> chore(client): update doc comment for handleSignInCallback

- packages/react-sample/src/index.tsx
Use `createRoot` instead of `ReactDOM.render` as the latter is deprecated in React 18.
https://react.dev/blog/2022/03/08/react-18-upgrade-guide#updates-to-client-rendering-apis
React sample works
~~- [ ] `.changeset`~~
~~- [ ] docs~~
OR
> chore(react-sample): use createRoot instead of ReactDOM render

- packages/browser/src/index.ts
- packages/client/src/index.ts
- packages/express/src/index.ts
- packages/next/src/index.ts
- packages/node/src/client.ts
- packages/node/src/index.ts
- packages/react/src/index.ts
- packages/vue/src/index.ts
Align the error exports in all js SDKs.
- Remove the export of `OidcError`. As currently it is only used internally and wrapped up by the `LogtoError` 
- Add the exports of `LogtoRequestError` to react and vue SDK
- Add all the missing error exports of Node SDKs. 
OR
> refactor: align the error exports in all js SDKs

- .changeset/angry-glasses-cough.md
- .gitignore
- packages/next/edge/index.ts
For Next.js Edge SDK, fix the bug: handle "config" param of `getLogtoContext` function.
This is a quick fix, will add unit tests for Edge SDK later in LOG-7370.
This PR fixes https://github.com/logto-io/logto/issues/4603
Local tested with sample.
> fix(next): fix get context params

- .changeset/fifty-paws-switch.md
- packages/client/src/index.test.ts
- packages/client/src/index.ts
reuse `getAccessToken()` Promise when there's an ongoing one to avoid multiple calls to the server
added unit tests, also tested locally
> refactor(client): reuse getAccessToken promise

- .changeset/good-radios-brake.md
- packages/js/src/utils/id-token.test.ts
- packages/js/src/utils/id-token.ts
Increase ID token issued-at-time tolerance (iat claim) to 5 minutes. This change helps mitigate the potential "Invalid issued at time in the ID token" failure when the client system time is not synced with the world time.
N/A
> refactor(js): increase ID token issued-at-time tolerance (iat) to 5 mins

- packages/next-sample/pages/profile-ssr.tsx
The correct redirect location should be `'/api/logto/sign-in'` instead of `'/api/logto/login'`.
I am not sure whether `export default logtoClient.handleAuthRoutes()` has changed route definition, the correct sign in route should be `/sign-in` instead of `/login`.
Ref: https://github.com/logto-io/logto/blob/f539b0851d42eba974032582a8094a540c9f1246/packages/console/src/assets/docs/guides/web-next/README.mdx#L97
> fix(next-sample): revise nextjs sample profile-ssr page redirect location

- .changeset/gold-snails-exercise.md
- packages/client/src/index.ts
- packages/client/src/mock.ts
- packages/js/package.json
- packages/node/edge/index.ts
- pnpm-lock.yaml
Use `btoa` function in NodeJS environment. Although this is deprecated, but it still works. 
`Buffer` is not available in some edge runtime, for example, in Cloudflare Pages, it should be imported through:
```
import { Buffer } from 'node:buffer";
```
But this import will fail in browser environment.
Also updated the package `@silverhand/essentials`, see https://github.com/silverhand-io/essentials/pull/58
The new version of `@silverhand/essentials` causes some issues with types, to bypass these, use explicit type annotations.
Pass existing tests.
> refactor(js,client,node): use btoa to replace buffer

- packages/next-server-actions-sample/app/page.tsx
- packages/next-server-actions-sample/libraries/logto.ts
In Next.js (Server Actions) sample package, add "configs" parameter and usage examle to "getLogtoContext".
Local tested.
> fix(next-server-actions-sample): add configs to get logto context

- .changeset/sharp-vans-collect.md
- packages/browser/package.json
- packages/client/package.json
- packages/js/package.json
- packages/node/package.json
- packages/react/package.json
- packages/vue/package.json
- pnpm-lock.yaml
Bump `@silverhand/essentials` to v2.8.7, which adds node 20 LTS support.
fixes #613 
~~- [ ] necessary TSDoc comments~~
> chore: update dependency @silverhand/essentials to v2.8.7

- .changeset/wicked-peas-destroy.md
- packages/react/package.json
- packages/react/src/context.tsx
- packages/react/src/hooks/index.test.tsx
- packages/react/src/hooks/index.ts
- packages/react/src/index.ts
- packages/react/src/provider.tsx
- pnpm-lock.yaml
- remove `useLoadingState`, leave the logic inside the context since they are generic.
- export more useful `isLoading` and `setIsLoading` from Logto context.
- export `LogtoContext` from the package
tested in Logto demo app. works as expected.
> refactor(react)!: refactor LogtoContextProps and LogtoContext

- .gitignore
- packages/angular-sample/README.md
- packages/angular-sample/package.json
since we removed Angular sample from the workspace, the `workspace:` protocol is no longer valid. update the protocol and readme accordingly
`pnpm i --ignore-workspace` installed packages and created `pnpm-lock.yaml` in the Angular sample project folder
> refactor: fix pnpm installation issue for angular sample

- .changeset/shy-monkeys-tease.md
- packages/next/edge/index.ts
- packages/next/src/index.ts
When access token changed (new one issued), the session will change with new token map as well, need to set new cookie by calling "storage.save()".
No need to change "server actions" SDK because the cookie is not managed inside the SDK, and the server action can not always call "setCookie".
Local tested, after 1 hour when access token expires, "set-cookie" is found in response header.
> fix(next): refresh cookie ttl when access token change

- .changeset/green-dingos-grin.md
- .changeset/small-cows-act.md
- .gitignore
- packages/node/package.json
- packages/node/src/index.ts
- packages/node/src/utils/cookie-storage.test.ts
- packages/node/src/utils/cookie-storage.ts
- packages/node/src/utils/promise-queue.test.ts
- packages/node/src/utils/promise-queue.ts
- packages/node/src/utils/session.test.ts
- packages/sveltekit-sample/package.json
- packages/sveltekit/package.json
- packages/sveltekit/src/index.test.ts
- packages/sveltekit/src/index.ts
- packages/vue-sample/package.json
- pnpm-lock.yaml
- implement reusable `CookieStorage` for Node environment (extracted from `@logto/sveltekit`)
- remove `node-fetch` from `@logto/node` (Node comes with native fetch from 17)
- minor package metadata updates
- implement a simple Promise queue as `p-queue` is ESM only but we still target CJS
unit tests + local sign-in/out
> refactor: implement `CookieStorage` for node sdk

- .changeset/afraid-socks-lie.md
- packages/nuxt/src/runtime/server/event-handler.ts
explicitly import `defineEventHandler` from h3 to fix the runtime error. fix #647.
after update, the nuxt project can build successfully
> fix(nuxt): import `defineEventHandler` from h3

- .changeset/strange-chairs-appear.md
- packages/client/src/client.ts
- packages/client/src/index.sign-in.test.ts
- packages/client/src/mock.ts
- packages/js/src/consts/index.ts
- packages/js/src/core/sign-in.test.ts
- packages/js/src/core/sign-in.ts
Support `login_hint` param on sign-in.
Tested with React sample project, and the `login_hint` param was appended in the sign-in URL properly when navigating to Logto sign-in experience page.
~~- [ ] integration tests'~~
> feat(js,client): support login_hint param on sign-in

- .changeset/polite-masks-judge.md
- packages/next/edge/index.ts
- packages/next/server-actions/cookie.ts
- packages/next/src/index.ts
In Next.js SDK, if cookie secure config is set to true, will add "SameSite=Lax".
There is "CookieStorage" in this project, but it turned out to be not easy to refactor. Created an issue to track, will refactor later.
Local tested.
> fix(next): set cookie samesite when the config is secure

- .changeset/silly-grapes-fold.md
- packages/client/src/client.ts
- packages/js/src/consts/index.ts
- packages/js/src/core/sign-in.test.ts
- packages/js/src/core/sign-in.ts
- packages/js/src/types/index.ts
- support `firstScreen`, `directSignIn`, and `extraParams` for sign-in
- deprecate `interactionMode`
added test cases
> feat: support additional sign-in params

- .changeset/blue-dolls-turn.md
- .changeset/chilly-pets-walk.md
- .changeset/clean-games-lie.md
- packages/client/src/client.ts
- packages/js/src/core/sign-in.test.ts
- packages/js/src/core/sign-in.ts
- packages/react/src/hooks/index.test.tsx
- packages/react/src/hooks/index.ts
- overload signature cannot be picked up in react, this pull request fixes it.
- remove unsupported direct sign-in methods
- added unit test
- correctly infer the type
> refactor: fix types

- .changeset/curvy-ghosts-talk.md
- packages/client/src/client.ts
- packages/client/src/index.sign-in.test.ts
Support dynamically specifying `Prompt` on `signIn()` function. And the SDK should take the prompt from sign in function over the one pre-configured in logto configs.
UT
> feat(client): support specifying prompt on sign-in

- .changeset/fresh-impalas-glow.md
- packages/client/src/client.ts
- packages/node/src/client.ts
Add organizationId param to getAccessTokenClaims function.
Users can now pass an organizationId to the getAccessTokenClaims function, and this will be passed down to the getAccessToken function. This allows you to get the access token claims with scopes inherited from the specific organization.
Local tested.
> feat(client,node): add organizationId param to getAccessTokenClaims

- .changeset/spotty-readers-rule.md
- packages/node/src/client.ts
- packages/node/src/index.test.ts
- packages/node/src/types.ts
Add `accessTokenOrgnizationId` param to `getContext`, allowing users to set `orgniazation_id` when granting access token.
Local tested.
> feat(node): add access token organization id param to getContext

- .changeset/angry-beans-run.md
- packages/client/src/utils/memoize.ts
fixed #771
Fix the bug of granting mutiple organization tokens concurrently.
The function `getAccessToken` is memoized by arguments, but the `memorize` function will only take the first argument as the cache key, change to take all arguments.
Local tested.
> fix(client): fix memoize cache key

- .changeset/shiny-camels-sin.md
- packages/sveltekit/package.json
add svelte export key in package.json.
This will address `svelte/kit`  redirect  not working bug.  [ref](https://github.com/sveltejs/vite-plugin-svelte/issues/293)
> fix(svelte): add svelte export key in package.json

- .changeset/mighty-feet-look.md
- packages/remix/README.md
- packages/remix/src/framework/mocks.ts
- packages/remix/src/infrastructure/logto/handle-sign-up.ts
- packages/remix/src/infrastructure/logto/index.ts
- packages/remix/src/useCases/handleAuthRoutes/index.ts
- packages/remix/src/useCases/handleSignUp/HandleSignUpController.spec.ts
- packages/remix/src/useCases/handleSignUp/HandleSignUpController.ts
- packages/remix/src/useCases/handleSignUp/HandleSignUpUseCase.spec.ts
- packages/remix/src/useCases/handleSignUp/HandleSignUpUseCase.ts
- packages/remix/src/useCases/handleSignUp/index.ts
Add a sign up flow for Remix: https://github.com/logto-io/js/issues/722
I published an NPM package and using it in production: https://www.npmjs.com/package/@samos123/logto-remix
You can try it with:
```
npm install @samos123/logto-remix@2.1.10-sam1
```
Then use the following for auth routes:
```
import { logto } from "~/services/authentication";
export const loader = logto.handleAuthRoutes({
"sign-in": {
path: "/api/logto/sign-in",
redirectBackTo: "/api/logto/callback", // The redirect URI just entered
},
"sign-in-callback": {
path: "/api/logto/callback",
redirectBackTo: "/",
},
"sign-out": {
path: "/api/logto/sign-out",
redirectBackTo: "/",
},
"sign-up": {
path: "/api/logto/sign-up",
redirectBackTo: "/api/logto/callback", // The redirect URI just entered
},
});
```
> feat: add support for sign up flow in Remix

- .changeset/afraid-tables-explain.md
- packages/sveltekit/src/index.test.ts
- packages/sveltekit/src/index.ts
introduce custom local storage support and error handling for getUserInfo
1. Introduce a new `storage` option in `hookConfig` that allows a custom local storage to be passed into `logtoClient`. This will supersede the default `CookieStorage` for storing session and token data. If a custom `storage` is provided, the `cookieConfig` settings can be disregarded.
2. Add a new `onGetUserInfoError` callback in `hookConfig` for custom error handling when `getUserInfo` or `getIdTokenClaims` operations fail. By default, a 500 server error will be thrown.
This PR will address the following feedbacks from the Logto community:
- Large cookie exception if a large number of tokens are cached. 
- Unable to catch the error thrown by the `getUserInfo` flow in the `handleLogto` method. 
test lcoally
> feat(sveltekit): add support for custom storage and getUserInfo error handling

- .changeset/thin-walls-play.md
- packages/client/src/adapter/defaults.test.ts
- packages/client/src/adapter/defaults.ts
- packages/client/src/client.ts
- packages/client/src/index.constructor.test.ts
- support clock tolerance config in `DefaultJwtVerifier`
- allow set `jwtVerifier` after `LogtoClient` instance created
unit test added.
> feat(client): support clock tolerance config

- packages/next-app-dir-sample/app/api/logto/sign-out/route.ts
The `/api/logto/sign-out` route is missing, this commit fix it, otherwise it will lead to a 404 not found.
The next.js app dir sample project is missing `/api/logto/sign-out` page route, and when user clicks sign-out button, it will lead to a 404 not found page.
Demo before fix:
https://github.com/logto-io/js/assets/1164623/a4358f5f-5ce7-4fef-8d82-87cef49917eb
> fix: add missing sign out page route for next.js app dir sample

- .changeset/short-moose-sleep.md
- packages/client/src/utils/requester.test.ts
- packages/client/src/utils/requester.ts
the response error has been mistakenly handled, causing the existing apps could not recognize the underlying errors.
updated test cases for simulating the real caess
> fix(client): fix request error handler

- .changeset/nine-actors-leave.md
- packages/next-server-actions-sample/app/get-access-token.tsx
- packages/next-server-actions-sample/app/logto.ts
- packages/next-server-actions-sample/app/page.tsx
- packages/next/server-actions/index.ts
Previously, in order to get access tokens (and organization tokens) in App Router, you'll use `getLogtoContext` with config `{ getAccessToken: true }`, this won't cache the token and will make a network request every time you call it. That is because Next.js does not allow to write cookies in the server side: HTTP does not allow setting cookies after streaming starts, so you must use .set() in a Server Action or Route Handler.
This change adds a new function `getAccessToken` for you to get the access token in a server action or a route handler. It will cache the token and only make a network request when the token is expired.
And also, this change adds a new function `getOrganizationToken` for you to get the organization token.
The original method is deprecated and will be removed in the …
> feat(next): add getAccessToken function to server actions

- .changeset/chilly-spiders-deliver.md
- packages/nuxt/src/runtime/server/event-handler.ts
Change the error of "empty configuration" to warning, because in some situations like static prerender, it makes sense to not setting any configurations. 
Local tested.
> fix(nuxt): change default configuration error to warning

- .changeset/angry-moons-tie.md
- packages/next/server-actions/index.ts
This PR improves the DX of the getAccessToken function, creating a new function that can be executed in the context of a React Server Component.
I'm not sure how to test this PR locally, I'd like to get support on this topic.
> feat(next): add getAccessTokenRSC function to server actions

- .changeset/perfect-rabbits-tap.md
- packages/js/src/core/user-info.ts
DevDependency not available in angular app
DevDependency import from **vitest** introduced in PR https://github.com/logto-io/js/pull/760 
This causes build problems in angular app as test runner is still **jest** 
Executed all unit tests
> fix: remove import from dev dependency

- .changeset/blue-phones-work.md
- packages/client/src/client.ts
- packages/js/src/consts/index.ts
- packages/js/src/core/sign-in.test.ts
- packages/js/src/core/sign-in.ts
- packages/js/src/types/index.ts
> Note: this pr will be merged once the first screen feature enhancement is released.
- We support identifier sign-in / sign-up / sso page as the first screen, so add related candidate values for the first screen param
- Add `identifiers` sign-in option config items to support generating identifier params for sign-in URL generation
UT && Test locally
Use the following sign-in options:
We'll be redirect to the related identifier sign-in page with identfiers filtered:
> feat: add first screen values and identifier config for sign-in options

- .changeset/poor-lizards-cheer.md
- packages/client/package.json
- packages/node/src/utils/cookie-storage.test.ts
- packages/node/src/utils/session.test.ts
Refactor `@logto/client` package exports condition for react-native.
Add `react-native` package export condition.
[Enabling package exports] feature (https://reactnative.dev/blog/2023/06/21/package-exports-support#enabling-package-exports-beta) in react-native is unstable and can cause issues.
Replace the `exports` in `@logto/client` package.json with the `react-native` [condition](https://reactnative.dev/blog/2023/06/21/package-exports-support#the-new-react-native-condition).
> refactor(js): refactor @logto/client package exports

- .changeset/nice-humans-fry.md
- packages/nuxt/src/runtime/server/event-handler.ts
- packages/nuxt/src/runtime/utils/types.ts
Support secure cookie storage for nuxt sdk, since the default `CookieStorage` behavior has changed in https://github.com/logto-io/js/pull/783
Test locally.
> feat!: support secure cookie storage for nuxt sdk

- .changeset/good-knives-clap.md
- packages/nuxt/src/runtime/server/event-handler.ts
- packages/nuxt/src/runtime/utils/constants.ts
- packages/nuxt/src/runtime/utils/types.ts
This pull request introduces a minor update to the @logto/nuxt package, enhancing the Nuxt SDK by supporting custom redirect URL settings.
This is particularly useful for applications deployed behind proxies or in environments with URL rewriting.
This PR also update the `CookieStorage` usage, because it was overlooked in the last update. 
Test locally.
> feat: support custom redirect base url for nuxt sdk

- .changeset/shaggy-cups-switch.md
- packages/node/src/utils/session.test.ts
- packages/node/src/utils/session.ts
The crypto parameter has been removed from the `unwrapSession` and `wrapSession` functions. With the introduction of Node.js 20, accessing crypto directly is now possible, which resolves issues related to `global is not defined` in edge runtimes.
Local tested with Node.js and Vercel edge runtime.
> fix(node): remove global.crypto

- .changeset/famous-islands-rule.md
- packages/js/src/core/sign-in.ts
- packages/js/src/types/index.ts
- packages/js/src/utils/angular.ts
Support extra sign-in params in angular
> feat(angular): support extra sign-in params in angular

- .changeset/many-peaches-kneel.md
- packages/browser/package.json
- packages/capacitor/package.json
- packages/client/package.json
- packages/express/package.json
- packages/express/test.cjs
- packages/js/package.json
- packages/next/package.json
- packages/next/test.cjs
- packages/node/package.json
- packages/node/test.cjs
- packages/react/package.json
- packages/remix/package.json
- packages/vue/package.json
- pnpm-lock.yaml
- rollup.config.js
- [BREAKING CHANGE] Drop common JS support
- Bump `camelcase-keys` to latest version.
Should also fix #618 since it's now pure ESM.
CI
> refactor: drop common JS support and become pure ESM

- .changeset/nine-meals-behave.md
- packages/nuxt/src/runtime/utils/constants.ts
fix the default value of customRedirectBaseUrl
Previously, it was set to `<replace-with-custom-redirect-base-url>`, which is not a valid value, and will cause 500 error.
Now the default value is removed because it's not a required value.
Local tested.
> fix(nuxt): remove default value of customRedirectBaseUrl

- packages/chrome-extension-sample/src/service-worker.ts
update chrome extension sample.
The chrome extension sample is actually using @logto/client and @logto/browser SDKs, and they already support `first_screen` and `direct_sign_in` authentication params. We update the sample here to let users know how to use the ability in their on use case.
Tested locally.
> chore: update chrome extension sample

- .changeset/chatty-dingos-confess.md
- packages/client/package.json
The new 0.4.0 react-native package release breaks if developers have unstable_enablePackageExports set to true, since https://github.com/logto-io/js/pull/791 uses root react-native fields in package.json.
While in office [React Native](https://reactnative.dev/blog/2023/06/21/package-exports-support#the-new-react-native-condition) and [metro](https://metrobundler.dev/docs/package-exports/#replacing-browser-and-react-native-fields) docs, enablePackageExports is going to be turned on by default in the future and the suggested way is to put react-native field under exports (instead of root).
To support both situations, we can add `react-native` field under both root and `exports`.
Discussion reference: https://github.com/logto-io/react-native/issues/20#issuecomment-2513375814
> feat: add package exports compatibility for react-native apps

- .changeset/neat-glasses-think.md
- packages/browser/src/storage.ts
support ssr for browser-based SDKs
Check if the `window` is defined, if not, ignore the storage operations, avoid breaking the server side rendering.
For this kind of SDKs, it doesn't make sense to be used in server side, because the auth state is usually stored in the client side which is not available in server side. So we can safely ignore the storage operations in server side.
fix https://github.com/logto-io/js/issues/890
Local tested.
> fix(browser): support ssr

- packages/nuxt/playground/nuxt.config.ts
- packages/nuxt/playground/server/api/auth/get-access-token.get.ts
- packages/nuxt/src/module.ts
In order to resolve the nuxt module in the server api (nitro) it is required to register an alias as decribed in https://github.com/logto-io/js/issues/909#issuecomment-2655507974.
Closes https://github.com/logto-io/js/issues/909
I tested the changes within an existing project locally.
> feat(nuxt): add alias to enable import in server api

- .changeset/hip-bears-swim.md
- packages/client/src/client.ts
- packages/client/src/index.test.ts
Improve error messages in Client SDK.
UT
> refactor: throw more detailed error messages in client SDK

- .changeset/tame-colts-sparkle.md
- packages/client/src/client.ts
- packages/client/src/index.sign-in.test.ts
Add new sign-in option to skip clearing cached tokens (ID token, refresh token, and access tokens) on calling `signIn()` method.
UT
> feat(client): add new sign-in option to skip clearing tokens on sign-in

- .changeset/wet-mails-do.md
- packages/js/package.json
Add react-native specific export entry declarations to the @logto/js package. This will address the issue https://github.com/logto-io/react-native/issues/47
React Native uses a different module resolution strategy compared to Node.js. We need to ensure that the paths we are using in the exports are compatible with how React Native resolves modules.
> fix(js): add react-native export declarations

- .changeset/cold-brooms-wait.md
- packages/angular-sample/package.json
- packages/angular-sample/src/app/app.component.ts
- packages/angular-sample/src/app/app.config.ts
- packages/angular/README.md
- packages/angular/package.json
- packages/angular/rollup.config.js
- packages/angular/src/index.ts
- packages/angular/tsconfig.build.json
- packages/angular/tsconfig.json
- packages/angular/vitest.config.ts
- packages/js/src/utils/index.ts
- pnpm-lock.yaml
fixed #956
The original Angular utilities required Angular-specific type annotations. They have been removed from `@logto/js` and moved to a dedicated package to resolve import issues when using `@logto/js`.
Local tested.
> refactor: split Angular utilities into a dedicated package

- .changeset/tame-nails-serve.md
- packages/capacitor/package.json
- pnpm-lock.yaml
bump @capacitor packages to v7.
tested locally on ios and android simulator
> chore(deps): bump @capacitor packages

- packages/next/src/index.test.ts
- packages/next/src/index.ts
In the default sign in callback route, check `postRedirectUri` before redirect.
Unit test and local tested.
> fix(next): support postRedirectUri when handling sign in
